/*
 * This file is generated by jOOQ.
*/
package com.nextcont.drive.jooq.db.mysql.tables.daos;


import com.nextcont.drive.jooq.db.mysql.tables.ColumnsPriv;
import com.nextcont.drive.jooq.db.mysql.tables.records.ColumnsPrivRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record5;
import org.jooq.impl.DAOImpl;


/**
 * Column privileges
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ColumnsPrivDao extends DAOImpl<ColumnsPrivRecord, com.nextcont.drive.jooq.db.mysql.tables.pojos.ColumnsPriv, Record5<String, String, String, String, String>> {

    /**
     * Create a new ColumnsPrivDao without any configuration
     */
    public ColumnsPrivDao() {
        super(ColumnsPriv.COLUMNS_PRIV, com.nextcont.drive.jooq.db.mysql.tables.pojos.ColumnsPriv.class);
    }

    /**
     * Create a new ColumnsPrivDao with an attached configuration
     */
    public ColumnsPrivDao(Configuration configuration) {
        super(ColumnsPriv.COLUMNS_PRIV, com.nextcont.drive.jooq.db.mysql.tables.pojos.ColumnsPriv.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record5<String, String, String, String, String> getId(com.nextcont.drive.jooq.db.mysql.tables.pojos.ColumnsPriv object) {
        return compositeKeyRecord(object.getHost(), object.getDb(), object.getUser(), object.getTableName(), object.getColumnName());
    }

    /**
     * Fetch records that have <code>Host IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.ColumnsPriv> fetchByHost(String... values) {
        return fetch(ColumnsPriv.COLUMNS_PRIV.HOST, values);
    }

    /**
     * Fetch records that have <code>Db IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.ColumnsPriv> fetchByDb(String... values) {
        return fetch(ColumnsPriv.COLUMNS_PRIV.DB, values);
    }

    /**
     * Fetch records that have <code>User IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.ColumnsPriv> fetchByUser(String... values) {
        return fetch(ColumnsPriv.COLUMNS_PRIV.USER, values);
    }

    /**
     * Fetch records that have <code>Table_name IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.ColumnsPriv> fetchByTableName(String... values) {
        return fetch(ColumnsPriv.COLUMNS_PRIV.TABLE_NAME, values);
    }

    /**
     * Fetch records that have <code>Column_name IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.ColumnsPriv> fetchByColumnName(String... values) {
        return fetch(ColumnsPriv.COLUMNS_PRIV.COLUMN_NAME, values);
    }

    /**
     * Fetch records that have <code>Timestamp IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.ColumnsPriv> fetchByTimestamp(Timestamp... values) {
        return fetch(ColumnsPriv.COLUMNS_PRIV.TIMESTAMP, values);
    }

    /**
     * Fetch records that have <code>Column_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.ColumnsPriv> fetchByColumnPriv(String... values) {
        return fetch(ColumnsPriv.COLUMNS_PRIV.COLUMN_PRIV, values);
    }
}
