/*
 * This file is generated by jOOQ.
*/
package com.nextcont.drive.jooq.db.mysql.tables.daos;


import com.nextcont.drive.jooq.db.mysql.enums.DbAlterPriv;
import com.nextcont.drive.jooq.db.mysql.enums.DbAlterRoutinePriv;
import com.nextcont.drive.jooq.db.mysql.enums.DbCreatePriv;
import com.nextcont.drive.jooq.db.mysql.enums.DbCreateRoutinePriv;
import com.nextcont.drive.jooq.db.mysql.enums.DbCreateTmpTablePriv;
import com.nextcont.drive.jooq.db.mysql.enums.DbCreateViewPriv;
import com.nextcont.drive.jooq.db.mysql.enums.DbDeletePriv;
import com.nextcont.drive.jooq.db.mysql.enums.DbDropPriv;
import com.nextcont.drive.jooq.db.mysql.enums.DbEventPriv;
import com.nextcont.drive.jooq.db.mysql.enums.DbExecutePriv;
import com.nextcont.drive.jooq.db.mysql.enums.DbGrantPriv;
import com.nextcont.drive.jooq.db.mysql.enums.DbIndexPriv;
import com.nextcont.drive.jooq.db.mysql.enums.DbInsertPriv;
import com.nextcont.drive.jooq.db.mysql.enums.DbLockTablesPriv;
import com.nextcont.drive.jooq.db.mysql.enums.DbReferencesPriv;
import com.nextcont.drive.jooq.db.mysql.enums.DbSelectPriv;
import com.nextcont.drive.jooq.db.mysql.enums.DbShowViewPriv;
import com.nextcont.drive.jooq.db.mysql.enums.DbTriggerPriv;
import com.nextcont.drive.jooq.db.mysql.enums.DbUpdatePriv;
import com.nextcont.drive.jooq.db.mysql.tables.Db;
import com.nextcont.drive.jooq.db.mysql.tables.records.DbRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record3;
import org.jooq.impl.DAOImpl;


/**
 * Database privileges
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbDao extends DAOImpl<DbRecord, com.nextcont.drive.jooq.db.mysql.tables.pojos.Db, Record3<String, String, String>> {

    /**
     * Create a new DbDao without any configuration
     */
    public DbDao() {
        super(Db.DB, com.nextcont.drive.jooq.db.mysql.tables.pojos.Db.class);
    }

    /**
     * Create a new DbDao with an attached configuration
     */
    public DbDao(Configuration configuration) {
        super(Db.DB, com.nextcont.drive.jooq.db.mysql.tables.pojos.Db.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record3<String, String, String> getId(com.nextcont.drive.jooq.db.mysql.tables.pojos.Db object) {
        return compositeKeyRecord(object.getHost(), object.getDb(), object.getUser());
    }

    /**
     * Fetch records that have <code>Host IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Db> fetchByHost(String... values) {
        return fetch(Db.DB.HOST, values);
    }

    /**
     * Fetch records that have <code>Db IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Db> fetchByDb(String... values) {
        return fetch(Db.DB.DB_, values);
    }

    /**
     * Fetch records that have <code>User IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Db> fetchByUser(String... values) {
        return fetch(Db.DB.USER, values);
    }

    /**
     * Fetch records that have <code>Select_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Db> fetchBySelectPriv(DbSelectPriv... values) {
        return fetch(Db.DB.SELECT_PRIV, values);
    }

    /**
     * Fetch records that have <code>Insert_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Db> fetchByInsertPriv(DbInsertPriv... values) {
        return fetch(Db.DB.INSERT_PRIV, values);
    }

    /**
     * Fetch records that have <code>Update_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Db> fetchByUpdatePriv(DbUpdatePriv... values) {
        return fetch(Db.DB.UPDATE_PRIV, values);
    }

    /**
     * Fetch records that have <code>Delete_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Db> fetchByDeletePriv(DbDeletePriv... values) {
        return fetch(Db.DB.DELETE_PRIV, values);
    }

    /**
     * Fetch records that have <code>Create_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Db> fetchByCreatePriv(DbCreatePriv... values) {
        return fetch(Db.DB.CREATE_PRIV, values);
    }

    /**
     * Fetch records that have <code>Drop_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Db> fetchByDropPriv(DbDropPriv... values) {
        return fetch(Db.DB.DROP_PRIV, values);
    }

    /**
     * Fetch records that have <code>Grant_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Db> fetchByGrantPriv(DbGrantPriv... values) {
        return fetch(Db.DB.GRANT_PRIV, values);
    }

    /**
     * Fetch records that have <code>References_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Db> fetchByReferencesPriv(DbReferencesPriv... values) {
        return fetch(Db.DB.REFERENCES_PRIV, values);
    }

    /**
     * Fetch records that have <code>Index_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Db> fetchByIndexPriv(DbIndexPriv... values) {
        return fetch(Db.DB.INDEX_PRIV, values);
    }

    /**
     * Fetch records that have <code>Alter_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Db> fetchByAlterPriv(DbAlterPriv... values) {
        return fetch(Db.DB.ALTER_PRIV, values);
    }

    /**
     * Fetch records that have <code>Create_tmp_table_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Db> fetchByCreateTmpTablePriv(DbCreateTmpTablePriv... values) {
        return fetch(Db.DB.CREATE_TMP_TABLE_PRIV, values);
    }

    /**
     * Fetch records that have <code>Lock_tables_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Db> fetchByLockTablesPriv(DbLockTablesPriv... values) {
        return fetch(Db.DB.LOCK_TABLES_PRIV, values);
    }

    /**
     * Fetch records that have <code>Create_view_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Db> fetchByCreateViewPriv(DbCreateViewPriv... values) {
        return fetch(Db.DB.CREATE_VIEW_PRIV, values);
    }

    /**
     * Fetch records that have <code>Show_view_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Db> fetchByShowViewPriv(DbShowViewPriv... values) {
        return fetch(Db.DB.SHOW_VIEW_PRIV, values);
    }

    /**
     * Fetch records that have <code>Create_routine_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Db> fetchByCreateRoutinePriv(DbCreateRoutinePriv... values) {
        return fetch(Db.DB.CREATE_ROUTINE_PRIV, values);
    }

    /**
     * Fetch records that have <code>Alter_routine_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Db> fetchByAlterRoutinePriv(DbAlterRoutinePriv... values) {
        return fetch(Db.DB.ALTER_ROUTINE_PRIV, values);
    }

    /**
     * Fetch records that have <code>Execute_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Db> fetchByExecutePriv(DbExecutePriv... values) {
        return fetch(Db.DB.EXECUTE_PRIV, values);
    }

    /**
     * Fetch records that have <code>Event_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Db> fetchByEventPriv(DbEventPriv... values) {
        return fetch(Db.DB.EVENT_PRIV, values);
    }

    /**
     * Fetch records that have <code>Trigger_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Db> fetchByTriggerPriv(DbTriggerPriv... values) {
        return fetch(Db.DB.TRIGGER_PRIV, values);
    }
}
