/*
 * This file is generated by jOOQ.
*/
package com.nextcont.drive.jooq.db.mysql.tables.daos;


import com.nextcont.drive.jooq.db.mysql.enums.EventIntervalField;
import com.nextcont.drive.jooq.db.mysql.enums.EventOnCompletion;
import com.nextcont.drive.jooq.db.mysql.enums.EventStatus;
import com.nextcont.drive.jooq.db.mysql.tables.Event;
import com.nextcont.drive.jooq.db.mysql.tables.records.EventRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UInteger;


/**
 * Events
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventDao extends DAOImpl<EventRecord, com.nextcont.drive.jooq.db.mysql.tables.pojos.Event, Record2<String, String>> {

    /**
     * Create a new EventDao without any configuration
     */
    public EventDao() {
        super(Event.EVENT, com.nextcont.drive.jooq.db.mysql.tables.pojos.Event.class);
    }

    /**
     * Create a new EventDao with an attached configuration
     */
    public EventDao(Configuration configuration) {
        super(Event.EVENT, com.nextcont.drive.jooq.db.mysql.tables.pojos.Event.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<String, String> getId(com.nextcont.drive.jooq.db.mysql.tables.pojos.Event object) {
        return compositeKeyRecord(object.getDb(), object.getName());
    }

    /**
     * Fetch records that have <code>db IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Event> fetchByDb(String... values) {
        return fetch(Event.EVENT.DB, values);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Event> fetchByName(String... values) {
        return fetch(Event.EVENT.NAME, values);
    }

    /**
     * Fetch records that have <code>body IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Event> fetchByBody(byte[]... values) {
        return fetch(Event.EVENT.BODY, values);
    }

    /**
     * Fetch records that have <code>definer IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Event> fetchByDefiner(String... values) {
        return fetch(Event.EVENT.DEFINER, values);
    }

    /**
     * Fetch records that have <code>execute_at IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Event> fetchByExecuteAt(Timestamp... values) {
        return fetch(Event.EVENT.EXECUTE_AT, values);
    }

    /**
     * Fetch records that have <code>interval_value IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Event> fetchByIntervalValue(Integer... values) {
        return fetch(Event.EVENT.INTERVAL_VALUE, values);
    }

    /**
     * Fetch records that have <code>interval_field IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Event> fetchByIntervalField(EventIntervalField... values) {
        return fetch(Event.EVENT.INTERVAL_FIELD, values);
    }

    /**
     * Fetch records that have <code>created IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Event> fetchByCreated(Timestamp... values) {
        return fetch(Event.EVENT.CREATED, values);
    }

    /**
     * Fetch records that have <code>modified IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Event> fetchByModified(Timestamp... values) {
        return fetch(Event.EVENT.MODIFIED, values);
    }

    /**
     * Fetch records that have <code>last_executed IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Event> fetchByLastExecuted(Timestamp... values) {
        return fetch(Event.EVENT.LAST_EXECUTED, values);
    }

    /**
     * Fetch records that have <code>starts IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Event> fetchByStarts(Timestamp... values) {
        return fetch(Event.EVENT.STARTS, values);
    }

    /**
     * Fetch records that have <code>ends IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Event> fetchByEnds(Timestamp... values) {
        return fetch(Event.EVENT.ENDS, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Event> fetchByStatus(EventStatus... values) {
        return fetch(Event.EVENT.STATUS, values);
    }

    /**
     * Fetch records that have <code>on_completion IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Event> fetchByOnCompletion(EventOnCompletion... values) {
        return fetch(Event.EVENT.ON_COMPLETION, values);
    }

    /**
     * Fetch records that have <code>sql_mode IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Event> fetchBySqlMode(String... values) {
        return fetch(Event.EVENT.SQL_MODE, values);
    }

    /**
     * Fetch records that have <code>comment IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Event> fetchByComment(String... values) {
        return fetch(Event.EVENT.COMMENT, values);
    }

    /**
     * Fetch records that have <code>originator IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Event> fetchByOriginator(UInteger... values) {
        return fetch(Event.EVENT.ORIGINATOR, values);
    }

    /**
     * Fetch records that have <code>time_zone IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Event> fetchByTimeZone(String... values) {
        return fetch(Event.EVENT.TIME_ZONE, values);
    }

    /**
     * Fetch records that have <code>character_set_client IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Event> fetchByCharacterSetClient(String... values) {
        return fetch(Event.EVENT.CHARACTER_SET_CLIENT, values);
    }

    /**
     * Fetch records that have <code>collation_connection IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Event> fetchByCollationConnection(String... values) {
        return fetch(Event.EVENT.COLLATION_CONNECTION, values);
    }

    /**
     * Fetch records that have <code>db_collation IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Event> fetchByDbCollation(String... values) {
        return fetch(Event.EVENT.DB_COLLATION, values);
    }

    /**
     * Fetch records that have <code>body_utf8 IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Event> fetchByBodyUtf8(byte[]... values) {
        return fetch(Event.EVENT.BODY_UTF8, values);
    }
}
