/*
 * This file is generated by jOOQ.
*/
package com.nextcont.drive.jooq.db.mysql.tables.daos;


import com.nextcont.drive.jooq.db.mysql.tables.HelpRelation;
import com.nextcont.drive.jooq.db.mysql.tables.records.HelpRelationRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UInteger;


/**
 * keyword-topic relation
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HelpRelationDao extends DAOImpl<HelpRelationRecord, com.nextcont.drive.jooq.db.mysql.tables.pojos.HelpRelation, Record2<UInteger, UInteger>> {

    /**
     * Create a new HelpRelationDao without any configuration
     */
    public HelpRelationDao() {
        super(HelpRelation.HELP_RELATION, com.nextcont.drive.jooq.db.mysql.tables.pojos.HelpRelation.class);
    }

    /**
     * Create a new HelpRelationDao with an attached configuration
     */
    public HelpRelationDao(Configuration configuration) {
        super(HelpRelation.HELP_RELATION, com.nextcont.drive.jooq.db.mysql.tables.pojos.HelpRelation.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<UInteger, UInteger> getId(com.nextcont.drive.jooq.db.mysql.tables.pojos.HelpRelation object) {
        return compositeKeyRecord(object.getHelpKeywordId(), object.getHelpTopicId());
    }

    /**
     * Fetch records that have <code>help_topic_id IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.HelpRelation> fetchByHelpTopicId(UInteger... values) {
        return fetch(HelpRelation.HELP_RELATION.HELP_TOPIC_ID, values);
    }

    /**
     * Fetch records that have <code>help_keyword_id IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.HelpRelation> fetchByHelpKeywordId(UInteger... values) {
        return fetch(HelpRelation.HELP_RELATION.HELP_KEYWORD_ID, values);
    }
}
