/*
 * This file is generated by jOOQ.
*/
package com.nextcont.drive.jooq.db.mysql.tables.daos;


import com.nextcont.drive.jooq.db.mysql.enums.HostAlterPriv;
import com.nextcont.drive.jooq.db.mysql.enums.HostAlterRoutinePriv;
import com.nextcont.drive.jooq.db.mysql.enums.HostCreatePriv;
import com.nextcont.drive.jooq.db.mysql.enums.HostCreateRoutinePriv;
import com.nextcont.drive.jooq.db.mysql.enums.HostCreateTmpTablePriv;
import com.nextcont.drive.jooq.db.mysql.enums.HostCreateViewPriv;
import com.nextcont.drive.jooq.db.mysql.enums.HostDeletePriv;
import com.nextcont.drive.jooq.db.mysql.enums.HostDropPriv;
import com.nextcont.drive.jooq.db.mysql.enums.HostExecutePriv;
import com.nextcont.drive.jooq.db.mysql.enums.HostGrantPriv;
import com.nextcont.drive.jooq.db.mysql.enums.HostIndexPriv;
import com.nextcont.drive.jooq.db.mysql.enums.HostInsertPriv;
import com.nextcont.drive.jooq.db.mysql.enums.HostLockTablesPriv;
import com.nextcont.drive.jooq.db.mysql.enums.HostReferencesPriv;
import com.nextcont.drive.jooq.db.mysql.enums.HostSelectPriv;
import com.nextcont.drive.jooq.db.mysql.enums.HostShowViewPriv;
import com.nextcont.drive.jooq.db.mysql.enums.HostTriggerPriv;
import com.nextcont.drive.jooq.db.mysql.enums.HostUpdatePriv;
import com.nextcont.drive.jooq.db.mysql.tables.Host;
import com.nextcont.drive.jooq.db.mysql.tables.records.HostRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * Host privileges;  Merged with database privileges
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HostDao extends DAOImpl<HostRecord, com.nextcont.drive.jooq.db.mysql.tables.pojos.Host, Record2<String, String>> {

    /**
     * Create a new HostDao without any configuration
     */
    public HostDao() {
        super(Host.HOST, com.nextcont.drive.jooq.db.mysql.tables.pojos.Host.class);
    }

    /**
     * Create a new HostDao with an attached configuration
     */
    public HostDao(Configuration configuration) {
        super(Host.HOST, com.nextcont.drive.jooq.db.mysql.tables.pojos.Host.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<String, String> getId(com.nextcont.drive.jooq.db.mysql.tables.pojos.Host object) {
        return compositeKeyRecord(object.getHost(), object.getDb());
    }

    /**
     * Fetch records that have <code>Host IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Host> fetchByHost(String... values) {
        return fetch(Host.HOST.HOST_, values);
    }

    /**
     * Fetch records that have <code>Db IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Host> fetchByDb(String... values) {
        return fetch(Host.HOST.DB, values);
    }

    /**
     * Fetch records that have <code>Select_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Host> fetchBySelectPriv(HostSelectPriv... values) {
        return fetch(Host.HOST.SELECT_PRIV, values);
    }

    /**
     * Fetch records that have <code>Insert_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Host> fetchByInsertPriv(HostInsertPriv... values) {
        return fetch(Host.HOST.INSERT_PRIV, values);
    }

    /**
     * Fetch records that have <code>Update_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Host> fetchByUpdatePriv(HostUpdatePriv... values) {
        return fetch(Host.HOST.UPDATE_PRIV, values);
    }

    /**
     * Fetch records that have <code>Delete_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Host> fetchByDeletePriv(HostDeletePriv... values) {
        return fetch(Host.HOST.DELETE_PRIV, values);
    }

    /**
     * Fetch records that have <code>Create_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Host> fetchByCreatePriv(HostCreatePriv... values) {
        return fetch(Host.HOST.CREATE_PRIV, values);
    }

    /**
     * Fetch records that have <code>Drop_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Host> fetchByDropPriv(HostDropPriv... values) {
        return fetch(Host.HOST.DROP_PRIV, values);
    }

    /**
     * Fetch records that have <code>Grant_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Host> fetchByGrantPriv(HostGrantPriv... values) {
        return fetch(Host.HOST.GRANT_PRIV, values);
    }

    /**
     * Fetch records that have <code>References_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Host> fetchByReferencesPriv(HostReferencesPriv... values) {
        return fetch(Host.HOST.REFERENCES_PRIV, values);
    }

    /**
     * Fetch records that have <code>Index_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Host> fetchByIndexPriv(HostIndexPriv... values) {
        return fetch(Host.HOST.INDEX_PRIV, values);
    }

    /**
     * Fetch records that have <code>Alter_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Host> fetchByAlterPriv(HostAlterPriv... values) {
        return fetch(Host.HOST.ALTER_PRIV, values);
    }

    /**
     * Fetch records that have <code>Create_tmp_table_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Host> fetchByCreateTmpTablePriv(HostCreateTmpTablePriv... values) {
        return fetch(Host.HOST.CREATE_TMP_TABLE_PRIV, values);
    }

    /**
     * Fetch records that have <code>Lock_tables_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Host> fetchByLockTablesPriv(HostLockTablesPriv... values) {
        return fetch(Host.HOST.LOCK_TABLES_PRIV, values);
    }

    /**
     * Fetch records that have <code>Create_view_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Host> fetchByCreateViewPriv(HostCreateViewPriv... values) {
        return fetch(Host.HOST.CREATE_VIEW_PRIV, values);
    }

    /**
     * Fetch records that have <code>Show_view_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Host> fetchByShowViewPriv(HostShowViewPriv... values) {
        return fetch(Host.HOST.SHOW_VIEW_PRIV, values);
    }

    /**
     * Fetch records that have <code>Create_routine_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Host> fetchByCreateRoutinePriv(HostCreateRoutinePriv... values) {
        return fetch(Host.HOST.CREATE_ROUTINE_PRIV, values);
    }

    /**
     * Fetch records that have <code>Alter_routine_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Host> fetchByAlterRoutinePriv(HostAlterRoutinePriv... values) {
        return fetch(Host.HOST.ALTER_ROUTINE_PRIV, values);
    }

    /**
     * Fetch records that have <code>Execute_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Host> fetchByExecutePriv(HostExecutePriv... values) {
        return fetch(Host.HOST.EXECUTE_PRIV, values);
    }

    /**
     * Fetch records that have <code>Trigger_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.Host> fetchByTriggerPriv(HostTriggerPriv... values) {
        return fetch(Host.HOST.TRIGGER_PRIV, values);
    }
}
