/*
 * This file is generated by jOOQ.
*/
package com.nextcont.drive.jooq.db.mysql.tables.daos;


import com.nextcont.drive.jooq.db.mysql.tables.TablesPriv;
import com.nextcont.drive.jooq.db.mysql.tables.records.TablesPrivRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record4;
import org.jooq.impl.DAOImpl;


/**
 * Table privileges
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TablesPrivDao extends DAOImpl<TablesPrivRecord, com.nextcont.drive.jooq.db.mysql.tables.pojos.TablesPriv, Record4<String, String, String, String>> {

    /**
     * Create a new TablesPrivDao without any configuration
     */
    public TablesPrivDao() {
        super(TablesPriv.TABLES_PRIV, com.nextcont.drive.jooq.db.mysql.tables.pojos.TablesPriv.class);
    }

    /**
     * Create a new TablesPrivDao with an attached configuration
     */
    public TablesPrivDao(Configuration configuration) {
        super(TablesPriv.TABLES_PRIV, com.nextcont.drive.jooq.db.mysql.tables.pojos.TablesPriv.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record4<String, String, String, String> getId(com.nextcont.drive.jooq.db.mysql.tables.pojos.TablesPriv object) {
        return compositeKeyRecord(object.getHost(), object.getDb(), object.getUser(), object.getTableName());
    }

    /**
     * Fetch records that have <code>Host IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.TablesPriv> fetchByHost(String... values) {
        return fetch(TablesPriv.TABLES_PRIV.HOST, values);
    }

    /**
     * Fetch records that have <code>Db IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.TablesPriv> fetchByDb(String... values) {
        return fetch(TablesPriv.TABLES_PRIV.DB, values);
    }

    /**
     * Fetch records that have <code>User IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.TablesPriv> fetchByUser(String... values) {
        return fetch(TablesPriv.TABLES_PRIV.USER, values);
    }

    /**
     * Fetch records that have <code>Table_name IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.TablesPriv> fetchByTableName(String... values) {
        return fetch(TablesPriv.TABLES_PRIV.TABLE_NAME, values);
    }

    /**
     * Fetch records that have <code>Grantor IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.TablesPriv> fetchByGrantor(String... values) {
        return fetch(TablesPriv.TABLES_PRIV.GRANTOR, values);
    }

    /**
     * Fetch records that have <code>Timestamp IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.TablesPriv> fetchByTimestamp(Timestamp... values) {
        return fetch(TablesPriv.TABLES_PRIV.TIMESTAMP, values);
    }

    /**
     * Fetch records that have <code>Table_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.TablesPriv> fetchByTablePriv(String... values) {
        return fetch(TablesPriv.TABLES_PRIV.TABLE_PRIV, values);
    }

    /**
     * Fetch records that have <code>Column_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.TablesPriv> fetchByColumnPriv(String... values) {
        return fetch(TablesPriv.TABLES_PRIV.COLUMN_PRIV, values);
    }
}
