/*
 * This file is generated by jOOQ.
*/
package com.nextcont.drive.jooq.db.mysql.tables.daos;


import com.nextcont.drive.jooq.db.mysql.tables.TimeZoneLeapSecond;
import com.nextcont.drive.jooq.db.mysql.tables.records.TimeZoneLeapSecondRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * Leap seconds information for time zones
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TimeZoneLeapSecondDao extends DAOImpl<TimeZoneLeapSecondRecord, com.nextcont.drive.jooq.db.mysql.tables.pojos.TimeZoneLeapSecond, Long> {

    /**
     * Create a new TimeZoneLeapSecondDao without any configuration
     */
    public TimeZoneLeapSecondDao() {
        super(TimeZoneLeapSecond.TIME_ZONE_LEAP_SECOND, com.nextcont.drive.jooq.db.mysql.tables.pojos.TimeZoneLeapSecond.class);
    }

    /**
     * Create a new TimeZoneLeapSecondDao with an attached configuration
     */
    public TimeZoneLeapSecondDao(Configuration configuration) {
        super(TimeZoneLeapSecond.TIME_ZONE_LEAP_SECOND, com.nextcont.drive.jooq.db.mysql.tables.pojos.TimeZoneLeapSecond.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.nextcont.drive.jooq.db.mysql.tables.pojos.TimeZoneLeapSecond object) {
        return object.getTransitionTime();
    }

    /**
     * Fetch records that have <code>Transition_time IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.TimeZoneLeapSecond> fetchByTransitionTime(Long... values) {
        return fetch(TimeZoneLeapSecond.TIME_ZONE_LEAP_SECOND.TRANSITION_TIME, values);
    }

    /**
     * Fetch a unique record that has <code>Transition_time = value</code>
     */
    public com.nextcont.drive.jooq.db.mysql.tables.pojos.TimeZoneLeapSecond fetchOneByTransitionTime(Long value) {
        return fetchOne(TimeZoneLeapSecond.TIME_ZONE_LEAP_SECOND.TRANSITION_TIME, value);
    }

    /**
     * Fetch records that have <code>Correction IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.TimeZoneLeapSecond> fetchByCorrection(Integer... values) {
        return fetch(TimeZoneLeapSecond.TIME_ZONE_LEAP_SECOND.CORRECTION, values);
    }
}
