/*
 * This file is generated by jOOQ.
*/
package com.nextcont.drive.jooq.db.mysql.tables.daos;


import com.nextcont.drive.jooq.db.mysql.enums.UserAlterPriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserAlterRoutinePriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserCreatePriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserCreateRoutinePriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserCreateTmpTablePriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserCreateUserPriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserCreateViewPriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserDeletePriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserDropPriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserEventPriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserExecutePriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserFilePriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserGrantPriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserIndexPriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserInsertPriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserLockTablesPriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserProcessPriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserReferencesPriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserReloadPriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserReplClientPriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserReplSlavePriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserSelectPriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserShowDbPriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserShowViewPriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserShutdownPriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserSslType;
import com.nextcont.drive.jooq.db.mysql.enums.UserSuperPriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserTriggerPriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserUpdatePriv;
import com.nextcont.drive.jooq.db.mysql.tables.User;
import com.nextcont.drive.jooq.db.mysql.tables.records.UserRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UInteger;


/**
 * Users and global privileges
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserDao extends DAOImpl<UserRecord, com.nextcont.drive.jooq.db.mysql.tables.pojos.User, Record2<String, String>> {

    /**
     * Create a new UserDao without any configuration
     */
    public UserDao() {
        super(User.USER, com.nextcont.drive.jooq.db.mysql.tables.pojos.User.class);
    }

    /**
     * Create a new UserDao with an attached configuration
     */
    public UserDao(Configuration configuration) {
        super(User.USER, com.nextcont.drive.jooq.db.mysql.tables.pojos.User.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<String, String> getId(com.nextcont.drive.jooq.db.mysql.tables.pojos.User object) {
        return compositeKeyRecord(object.getHost(), object.getUser());
    }

    /**
     * Fetch records that have <code>Host IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.User> fetchByHost(String... values) {
        return fetch(User.USER.HOST, values);
    }

    /**
     * Fetch records that have <code>User IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.User> fetchByUser(String... values) {
        return fetch(User.USER.USER_, values);
    }

    /**
     * Fetch records that have <code>Password IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.User> fetchByPassword(String... values) {
        return fetch(User.USER.PASSWORD, values);
    }

    /**
     * Fetch records that have <code>Select_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.User> fetchBySelectPriv(UserSelectPriv... values) {
        return fetch(User.USER.SELECT_PRIV, values);
    }

    /**
     * Fetch records that have <code>Insert_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.User> fetchByInsertPriv(UserInsertPriv... values) {
        return fetch(User.USER.INSERT_PRIV, values);
    }

    /**
     * Fetch records that have <code>Update_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.User> fetchByUpdatePriv(UserUpdatePriv... values) {
        return fetch(User.USER.UPDATE_PRIV, values);
    }

    /**
     * Fetch records that have <code>Delete_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.User> fetchByDeletePriv(UserDeletePriv... values) {
        return fetch(User.USER.DELETE_PRIV, values);
    }

    /**
     * Fetch records that have <code>Create_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.User> fetchByCreatePriv(UserCreatePriv... values) {
        return fetch(User.USER.CREATE_PRIV, values);
    }

    /**
     * Fetch records that have <code>Drop_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.User> fetchByDropPriv(UserDropPriv... values) {
        return fetch(User.USER.DROP_PRIV, values);
    }

    /**
     * Fetch records that have <code>Reload_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.User> fetchByReloadPriv(UserReloadPriv... values) {
        return fetch(User.USER.RELOAD_PRIV, values);
    }

    /**
     * Fetch records that have <code>Shutdown_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.User> fetchByShutdownPriv(UserShutdownPriv... values) {
        return fetch(User.USER.SHUTDOWN_PRIV, values);
    }

    /**
     * Fetch records that have <code>Process_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.User> fetchByProcessPriv(UserProcessPriv... values) {
        return fetch(User.USER.PROCESS_PRIV, values);
    }

    /**
     * Fetch records that have <code>File_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.User> fetchByFilePriv(UserFilePriv... values) {
        return fetch(User.USER.FILE_PRIV, values);
    }

    /**
     * Fetch records that have <code>Grant_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.User> fetchByGrantPriv(UserGrantPriv... values) {
        return fetch(User.USER.GRANT_PRIV, values);
    }

    /**
     * Fetch records that have <code>References_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.User> fetchByReferencesPriv(UserReferencesPriv... values) {
        return fetch(User.USER.REFERENCES_PRIV, values);
    }

    /**
     * Fetch records that have <code>Index_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.User> fetchByIndexPriv(UserIndexPriv... values) {
        return fetch(User.USER.INDEX_PRIV, values);
    }

    /**
     * Fetch records that have <code>Alter_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.User> fetchByAlterPriv(UserAlterPriv... values) {
        return fetch(User.USER.ALTER_PRIV, values);
    }

    /**
     * Fetch records that have <code>Show_db_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.User> fetchByShowDbPriv(UserShowDbPriv... values) {
        return fetch(User.USER.SHOW_DB_PRIV, values);
    }

    /**
     * Fetch records that have <code>Super_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.User> fetchBySuperPriv(UserSuperPriv... values) {
        return fetch(User.USER.SUPER_PRIV, values);
    }

    /**
     * Fetch records that have <code>Create_tmp_table_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.User> fetchByCreateTmpTablePriv(UserCreateTmpTablePriv... values) {
        return fetch(User.USER.CREATE_TMP_TABLE_PRIV, values);
    }

    /**
     * Fetch records that have <code>Lock_tables_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.User> fetchByLockTablesPriv(UserLockTablesPriv... values) {
        return fetch(User.USER.LOCK_TABLES_PRIV, values);
    }

    /**
     * Fetch records that have <code>Execute_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.User> fetchByExecutePriv(UserExecutePriv... values) {
        return fetch(User.USER.EXECUTE_PRIV, values);
    }

    /**
     * Fetch records that have <code>Repl_slave_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.User> fetchByReplSlavePriv(UserReplSlavePriv... values) {
        return fetch(User.USER.REPL_SLAVE_PRIV, values);
    }

    /**
     * Fetch records that have <code>Repl_client_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.User> fetchByReplClientPriv(UserReplClientPriv... values) {
        return fetch(User.USER.REPL_CLIENT_PRIV, values);
    }

    /**
     * Fetch records that have <code>Create_view_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.User> fetchByCreateViewPriv(UserCreateViewPriv... values) {
        return fetch(User.USER.CREATE_VIEW_PRIV, values);
    }

    /**
     * Fetch records that have <code>Show_view_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.User> fetchByShowViewPriv(UserShowViewPriv... values) {
        return fetch(User.USER.SHOW_VIEW_PRIV, values);
    }

    /**
     * Fetch records that have <code>Create_routine_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.User> fetchByCreateRoutinePriv(UserCreateRoutinePriv... values) {
        return fetch(User.USER.CREATE_ROUTINE_PRIV, values);
    }

    /**
     * Fetch records that have <code>Alter_routine_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.User> fetchByAlterRoutinePriv(UserAlterRoutinePriv... values) {
        return fetch(User.USER.ALTER_ROUTINE_PRIV, values);
    }

    /**
     * Fetch records that have <code>Create_user_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.User> fetchByCreateUserPriv(UserCreateUserPriv... values) {
        return fetch(User.USER.CREATE_USER_PRIV, values);
    }

    /**
     * Fetch records that have <code>Event_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.User> fetchByEventPriv(UserEventPriv... values) {
        return fetch(User.USER.EVENT_PRIV, values);
    }

    /**
     * Fetch records that have <code>Trigger_priv IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.User> fetchByTriggerPriv(UserTriggerPriv... values) {
        return fetch(User.USER.TRIGGER_PRIV, values);
    }

    /**
     * Fetch records that have <code>ssl_type IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.User> fetchBySslType(UserSslType... values) {
        return fetch(User.USER.SSL_TYPE, values);
    }

    /**
     * Fetch records that have <code>ssl_cipher IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.User> fetchBySslCipher(byte[]... values) {
        return fetch(User.USER.SSL_CIPHER, values);
    }

    /**
     * Fetch records that have <code>x509_issuer IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.User> fetchByX509Issuer(byte[]... values) {
        return fetch(User.USER.X509_ISSUER, values);
    }

    /**
     * Fetch records that have <code>x509_subject IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.User> fetchByX509Subject(byte[]... values) {
        return fetch(User.USER.X509_SUBJECT, values);
    }

    /**
     * Fetch records that have <code>max_questions IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.User> fetchByMaxQuestions(UInteger... values) {
        return fetch(User.USER.MAX_QUESTIONS, values);
    }

    /**
     * Fetch records that have <code>max_updates IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.User> fetchByMaxUpdates(UInteger... values) {
        return fetch(User.USER.MAX_UPDATES, values);
    }

    /**
     * Fetch records that have <code>max_connections IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.User> fetchByMaxConnections(UInteger... values) {
        return fetch(User.USER.MAX_CONNECTIONS, values);
    }

    /**
     * Fetch records that have <code>max_user_connections IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.mysql.tables.pojos.User> fetchByMaxUserConnections(UInteger... values) {
        return fetch(User.USER.MAX_USER_CONNECTIONS, values);
    }
}
