/*
 * This file is generated by jOOQ.
*/
package com.nextcont.drive.jooq.db.information_schema;


import com.nextcont.drive.jooq.db.DefaultCatalog;
import com.nextcont.drive.jooq.db.information_schema.tables.CharacterSets;
import com.nextcont.drive.jooq.db.information_schema.tables.CollationCharacterSetApplicability;
import com.nextcont.drive.jooq.db.information_schema.tables.Collations;
import com.nextcont.drive.jooq.db.information_schema.tables.ColumnPrivileges;
import com.nextcont.drive.jooq.db.information_schema.tables.Columns;
import com.nextcont.drive.jooq.db.information_schema.tables.Engines;
import com.nextcont.drive.jooq.db.information_schema.tables.Events;
import com.nextcont.drive.jooq.db.information_schema.tables.Files;
import com.nextcont.drive.jooq.db.information_schema.tables.GlobalStatus;
import com.nextcont.drive.jooq.db.information_schema.tables.GlobalVariables;
import com.nextcont.drive.jooq.db.information_schema.tables.KeyColumnUsage;
import com.nextcont.drive.jooq.db.information_schema.tables.Partitions;
import com.nextcont.drive.jooq.db.information_schema.tables.Plugins;
import com.nextcont.drive.jooq.db.information_schema.tables.Processlist;
import com.nextcont.drive.jooq.db.information_schema.tables.Profiling;
import com.nextcont.drive.jooq.db.information_schema.tables.ReferentialConstraints;
import com.nextcont.drive.jooq.db.information_schema.tables.Routines;
import com.nextcont.drive.jooq.db.information_schema.tables.SchemaPrivileges;
import com.nextcont.drive.jooq.db.information_schema.tables.Schemata;
import com.nextcont.drive.jooq.db.information_schema.tables.SessionStatus;
import com.nextcont.drive.jooq.db.information_schema.tables.SessionVariables;
import com.nextcont.drive.jooq.db.information_schema.tables.Statistics;
import com.nextcont.drive.jooq.db.information_schema.tables.TableConstraints;
import com.nextcont.drive.jooq.db.information_schema.tables.TablePrivileges;
import com.nextcont.drive.jooq.db.information_schema.tables.Tables;
import com.nextcont.drive.jooq.db.information_schema.tables.Triggers;
import com.nextcont.drive.jooq.db.information_schema.tables.UserPrivileges;
import com.nextcont.drive.jooq.db.information_schema.tables.Views;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InformationSchema extends SchemaImpl {

    private static final long serialVersionUID = -1179908170;

    /**
     * The reference instance of <code>information_schema</code>
     */
    public static final InformationSchema INFORMATION_SCHEMA = new InformationSchema();

    /**
     * The table <code>information_schema.CHARACTER_SETS</code>.
     */
    public final CharacterSets CHARACTER_SETS = com.nextcont.drive.jooq.db.information_schema.tables.CharacterSets.CHARACTER_SETS;

    /**
     * The table <code>information_schema.COLLATIONS</code>.
     */
    public final Collations COLLATIONS = com.nextcont.drive.jooq.db.information_schema.tables.Collations.COLLATIONS;

    /**
     * The table <code>information_schema.COLLATION_CHARACTER_SET_APPLICABILITY</code>.
     */
    public final CollationCharacterSetApplicability COLLATION_CHARACTER_SET_APPLICABILITY = com.nextcont.drive.jooq.db.information_schema.tables.CollationCharacterSetApplicability.COLLATION_CHARACTER_SET_APPLICABILITY;

    /**
     * The table <code>information_schema.COLUMNS</code>.
     */
    public final Columns COLUMNS = com.nextcont.drive.jooq.db.information_schema.tables.Columns.COLUMNS;

    /**
     * The table <code>information_schema.COLUMN_PRIVILEGES</code>.
     */
    public final ColumnPrivileges COLUMN_PRIVILEGES = com.nextcont.drive.jooq.db.information_schema.tables.ColumnPrivileges.COLUMN_PRIVILEGES;

    /**
     * The table <code>information_schema.ENGINES</code>.
     */
    public final Engines ENGINES = com.nextcont.drive.jooq.db.information_schema.tables.Engines.ENGINES;

    /**
     * The table <code>information_schema.EVENTS</code>.
     */
    public final Events EVENTS = com.nextcont.drive.jooq.db.information_schema.tables.Events.EVENTS;

    /**
     * The table <code>information_schema.FILES</code>.
     */
    public final Files FILES = com.nextcont.drive.jooq.db.information_schema.tables.Files.FILES;

    /**
     * The table <code>information_schema.GLOBAL_STATUS</code>.
     */
    public final GlobalStatus GLOBAL_STATUS = com.nextcont.drive.jooq.db.information_schema.tables.GlobalStatus.GLOBAL_STATUS;

    /**
     * The table <code>information_schema.GLOBAL_VARIABLES</code>.
     */
    public final GlobalVariables GLOBAL_VARIABLES = com.nextcont.drive.jooq.db.information_schema.tables.GlobalVariables.GLOBAL_VARIABLES;

    /**
     * The table <code>information_schema.KEY_COLUMN_USAGE</code>.
     */
    public final KeyColumnUsage KEY_COLUMN_USAGE = com.nextcont.drive.jooq.db.information_schema.tables.KeyColumnUsage.KEY_COLUMN_USAGE;

    /**
     * The table <code>information_schema.PARTITIONS</code>.
     */
    public final Partitions PARTITIONS = com.nextcont.drive.jooq.db.information_schema.tables.Partitions.PARTITIONS;

    /**
     * The table <code>information_schema.PLUGINS</code>.
     */
    public final Plugins PLUGINS = com.nextcont.drive.jooq.db.information_schema.tables.Plugins.PLUGINS;

    /**
     * The table <code>information_schema.PROCESSLIST</code>.
     */
    public final Processlist PROCESSLIST = com.nextcont.drive.jooq.db.information_schema.tables.Processlist.PROCESSLIST;

    /**
     * The table <code>information_schema.PROFILING</code>.
     */
    public final Profiling PROFILING = com.nextcont.drive.jooq.db.information_schema.tables.Profiling.PROFILING;

    /**
     * The table <code>information_schema.REFERENTIAL_CONSTRAINTS</code>.
     */
    public final ReferentialConstraints REFERENTIAL_CONSTRAINTS = com.nextcont.drive.jooq.db.information_schema.tables.ReferentialConstraints.REFERENTIAL_CONSTRAINTS;

    /**
     * The table <code>information_schema.ROUTINES</code>.
     */
    public final Routines ROUTINES = com.nextcont.drive.jooq.db.information_schema.tables.Routines.ROUTINES;

    /**
     * The table <code>information_schema.SCHEMATA</code>.
     */
    public final Schemata SCHEMATA = com.nextcont.drive.jooq.db.information_schema.tables.Schemata.SCHEMATA;

    /**
     * The table <code>information_schema.SCHEMA_PRIVILEGES</code>.
     */
    public final SchemaPrivileges SCHEMA_PRIVILEGES = com.nextcont.drive.jooq.db.information_schema.tables.SchemaPrivileges.SCHEMA_PRIVILEGES;

    /**
     * The table <code>information_schema.SESSION_STATUS</code>.
     */
    public final SessionStatus SESSION_STATUS = com.nextcont.drive.jooq.db.information_schema.tables.SessionStatus.SESSION_STATUS;

    /**
     * The table <code>information_schema.SESSION_VARIABLES</code>.
     */
    public final SessionVariables SESSION_VARIABLES = com.nextcont.drive.jooq.db.information_schema.tables.SessionVariables.SESSION_VARIABLES;

    /**
     * The table <code>information_schema.STATISTICS</code>.
     */
    public final Statistics STATISTICS = com.nextcont.drive.jooq.db.information_schema.tables.Statistics.STATISTICS;

    /**
     * The table <code>information_schema.TABLES</code>.
     */
    public final Tables TABLES = com.nextcont.drive.jooq.db.information_schema.tables.Tables.TABLES;

    /**
     * The table <code>information_schema.TABLE_CONSTRAINTS</code>.
     */
    public final TableConstraints TABLE_CONSTRAINTS = com.nextcont.drive.jooq.db.information_schema.tables.TableConstraints.TABLE_CONSTRAINTS;

    /**
     * The table <code>information_schema.TABLE_PRIVILEGES</code>.
     */
    public final TablePrivileges TABLE_PRIVILEGES = com.nextcont.drive.jooq.db.information_schema.tables.TablePrivileges.TABLE_PRIVILEGES;

    /**
     * The table <code>information_schema.TRIGGERS</code>.
     */
    public final Triggers TRIGGERS = com.nextcont.drive.jooq.db.information_schema.tables.Triggers.TRIGGERS;

    /**
     * The table <code>information_schema.USER_PRIVILEGES</code>.
     */
    public final UserPrivileges USER_PRIVILEGES = com.nextcont.drive.jooq.db.information_schema.tables.UserPrivileges.USER_PRIVILEGES;

    /**
     * The table <code>information_schema.VIEWS</code>.
     */
    public final Views VIEWS = com.nextcont.drive.jooq.db.information_schema.tables.Views.VIEWS;

    /**
     * No further instances allowed
     */
    private InformationSchema() {
        super("information_schema", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            CharacterSets.CHARACTER_SETS,
            Collations.COLLATIONS,
            CollationCharacterSetApplicability.COLLATION_CHARACTER_SET_APPLICABILITY,
            Columns.COLUMNS,
            ColumnPrivileges.COLUMN_PRIVILEGES,
            Engines.ENGINES,
            Events.EVENTS,
            Files.FILES,
            GlobalStatus.GLOBAL_STATUS,
            GlobalVariables.GLOBAL_VARIABLES,
            KeyColumnUsage.KEY_COLUMN_USAGE,
            Partitions.PARTITIONS,
            Plugins.PLUGINS,
            Processlist.PROCESSLIST,
            Profiling.PROFILING,
            ReferentialConstraints.REFERENTIAL_CONSTRAINTS,
            Routines.ROUTINES,
            Schemata.SCHEMATA,
            SchemaPrivileges.SCHEMA_PRIVILEGES,
            SessionStatus.SESSION_STATUS,
            SessionVariables.SESSION_VARIABLES,
            Statistics.STATISTICS,
            Tables.TABLES,
            TableConstraints.TABLE_CONSTRAINTS,
            TablePrivileges.TABLE_PRIVILEGES,
            Triggers.TRIGGERS,
            UserPrivileges.USER_PRIVILEGES,
            Views.VIEWS);
    }
}
