/*
 * This file is generated by jOOQ.
*/
package com.nextcont.drive.jooq.db.information_schema;


import com.nextcont.drive.jooq.db.information_schema.tables.CharacterSets;
import com.nextcont.drive.jooq.db.information_schema.tables.CollationCharacterSetApplicability;
import com.nextcont.drive.jooq.db.information_schema.tables.Collations;
import com.nextcont.drive.jooq.db.information_schema.tables.ColumnPrivileges;
import com.nextcont.drive.jooq.db.information_schema.tables.Columns;
import com.nextcont.drive.jooq.db.information_schema.tables.Engines;
import com.nextcont.drive.jooq.db.information_schema.tables.Events;
import com.nextcont.drive.jooq.db.information_schema.tables.Files;
import com.nextcont.drive.jooq.db.information_schema.tables.GlobalStatus;
import com.nextcont.drive.jooq.db.information_schema.tables.GlobalVariables;
import com.nextcont.drive.jooq.db.information_schema.tables.KeyColumnUsage;
import com.nextcont.drive.jooq.db.information_schema.tables.Partitions;
import com.nextcont.drive.jooq.db.information_schema.tables.Plugins;
import com.nextcont.drive.jooq.db.information_schema.tables.Processlist;
import com.nextcont.drive.jooq.db.information_schema.tables.Profiling;
import com.nextcont.drive.jooq.db.information_schema.tables.ReferentialConstraints;
import com.nextcont.drive.jooq.db.information_schema.tables.Routines;
import com.nextcont.drive.jooq.db.information_schema.tables.SchemaPrivileges;
import com.nextcont.drive.jooq.db.information_schema.tables.Schemata;
import com.nextcont.drive.jooq.db.information_schema.tables.SessionStatus;
import com.nextcont.drive.jooq.db.information_schema.tables.SessionVariables;
import com.nextcont.drive.jooq.db.information_schema.tables.Statistics;
import com.nextcont.drive.jooq.db.information_schema.tables.TableConstraints;
import com.nextcont.drive.jooq.db.information_schema.tables.TablePrivileges;
import com.nextcont.drive.jooq.db.information_schema.tables.Triggers;
import com.nextcont.drive.jooq.db.information_schema.tables.UserPrivileges;
import com.nextcont.drive.jooq.db.information_schema.tables.Views;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in information_schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>information_schema.CHARACTER_SETS</code>.
     */
    public static final CharacterSets CHARACTER_SETS = com.nextcont.drive.jooq.db.information_schema.tables.CharacterSets.CHARACTER_SETS;

    /**
     * The table <code>information_schema.COLLATIONS</code>.
     */
    public static final Collations COLLATIONS = com.nextcont.drive.jooq.db.information_schema.tables.Collations.COLLATIONS;

    /**
     * The table <code>information_schema.COLLATION_CHARACTER_SET_APPLICABILITY</code>.
     */
    public static final CollationCharacterSetApplicability COLLATION_CHARACTER_SET_APPLICABILITY = com.nextcont.drive.jooq.db.information_schema.tables.CollationCharacterSetApplicability.COLLATION_CHARACTER_SET_APPLICABILITY;

    /**
     * The table <code>information_schema.COLUMNS</code>.
     */
    public static final Columns COLUMNS = com.nextcont.drive.jooq.db.information_schema.tables.Columns.COLUMNS;

    /**
     * The table <code>information_schema.COLUMN_PRIVILEGES</code>.
     */
    public static final ColumnPrivileges COLUMN_PRIVILEGES = com.nextcont.drive.jooq.db.information_schema.tables.ColumnPrivileges.COLUMN_PRIVILEGES;

    /**
     * The table <code>information_schema.ENGINES</code>.
     */
    public static final Engines ENGINES = com.nextcont.drive.jooq.db.information_schema.tables.Engines.ENGINES;

    /**
     * The table <code>information_schema.EVENTS</code>.
     */
    public static final Events EVENTS = com.nextcont.drive.jooq.db.information_schema.tables.Events.EVENTS;

    /**
     * The table <code>information_schema.FILES</code>.
     */
    public static final Files FILES = com.nextcont.drive.jooq.db.information_schema.tables.Files.FILES;

    /**
     * The table <code>information_schema.GLOBAL_STATUS</code>.
     */
    public static final GlobalStatus GLOBAL_STATUS = com.nextcont.drive.jooq.db.information_schema.tables.GlobalStatus.GLOBAL_STATUS;

    /**
     * The table <code>information_schema.GLOBAL_VARIABLES</code>.
     */
    public static final GlobalVariables GLOBAL_VARIABLES = com.nextcont.drive.jooq.db.information_schema.tables.GlobalVariables.GLOBAL_VARIABLES;

    /**
     * The table <code>information_schema.KEY_COLUMN_USAGE</code>.
     */
    public static final KeyColumnUsage KEY_COLUMN_USAGE = com.nextcont.drive.jooq.db.information_schema.tables.KeyColumnUsage.KEY_COLUMN_USAGE;

    /**
     * The table <code>information_schema.PARTITIONS</code>.
     */
    public static final Partitions PARTITIONS = com.nextcont.drive.jooq.db.information_schema.tables.Partitions.PARTITIONS;

    /**
     * The table <code>information_schema.PLUGINS</code>.
     */
    public static final Plugins PLUGINS = com.nextcont.drive.jooq.db.information_schema.tables.Plugins.PLUGINS;

    /**
     * The table <code>information_schema.PROCESSLIST</code>.
     */
    public static final Processlist PROCESSLIST = com.nextcont.drive.jooq.db.information_schema.tables.Processlist.PROCESSLIST;

    /**
     * The table <code>information_schema.PROFILING</code>.
     */
    public static final Profiling PROFILING = com.nextcont.drive.jooq.db.information_schema.tables.Profiling.PROFILING;

    /**
     * The table <code>information_schema.REFERENTIAL_CONSTRAINTS</code>.
     */
    public static final ReferentialConstraints REFERENTIAL_CONSTRAINTS = com.nextcont.drive.jooq.db.information_schema.tables.ReferentialConstraints.REFERENTIAL_CONSTRAINTS;

    /**
     * The table <code>information_schema.ROUTINES</code>.
     */
    public static final Routines ROUTINES = com.nextcont.drive.jooq.db.information_schema.tables.Routines.ROUTINES;

    /**
     * The table <code>information_schema.SCHEMATA</code>.
     */
    public static final Schemata SCHEMATA = com.nextcont.drive.jooq.db.information_schema.tables.Schemata.SCHEMATA;

    /**
     * The table <code>information_schema.SCHEMA_PRIVILEGES</code>.
     */
    public static final SchemaPrivileges SCHEMA_PRIVILEGES = com.nextcont.drive.jooq.db.information_schema.tables.SchemaPrivileges.SCHEMA_PRIVILEGES;

    /**
     * The table <code>information_schema.SESSION_STATUS</code>.
     */
    public static final SessionStatus SESSION_STATUS = com.nextcont.drive.jooq.db.information_schema.tables.SessionStatus.SESSION_STATUS;

    /**
     * The table <code>information_schema.SESSION_VARIABLES</code>.
     */
    public static final SessionVariables SESSION_VARIABLES = com.nextcont.drive.jooq.db.information_schema.tables.SessionVariables.SESSION_VARIABLES;

    /**
     * The table <code>information_schema.STATISTICS</code>.
     */
    public static final Statistics STATISTICS = com.nextcont.drive.jooq.db.information_schema.tables.Statistics.STATISTICS;

    /**
     * The table <code>information_schema.TABLES</code>.
     */
    public static final com.nextcont.drive.jooq.db.information_schema.tables.Tables TABLES = com.nextcont.drive.jooq.db.information_schema.tables.Tables.TABLES;

    /**
     * The table <code>information_schema.TABLE_CONSTRAINTS</code>.
     */
    public static final TableConstraints TABLE_CONSTRAINTS = com.nextcont.drive.jooq.db.information_schema.tables.TableConstraints.TABLE_CONSTRAINTS;

    /**
     * The table <code>information_schema.TABLE_PRIVILEGES</code>.
     */
    public static final TablePrivileges TABLE_PRIVILEGES = com.nextcont.drive.jooq.db.information_schema.tables.TablePrivileges.TABLE_PRIVILEGES;

    /**
     * The table <code>information_schema.TRIGGERS</code>.
     */
    public static final Triggers TRIGGERS = com.nextcont.drive.jooq.db.information_schema.tables.Triggers.TRIGGERS;

    /**
     * The table <code>information_schema.USER_PRIVILEGES</code>.
     */
    public static final UserPrivileges USER_PRIVILEGES = com.nextcont.drive.jooq.db.information_schema.tables.UserPrivileges.USER_PRIVILEGES;

    /**
     * The table <code>information_schema.VIEWS</code>.
     */
    public static final Views VIEWS = com.nextcont.drive.jooq.db.information_schema.tables.Views.VIEWS;
}
