/*
 * This file is generated by jOOQ.
*/
package com.nextcont.drive.jooq.db.ecm_trans;


import com.nextcont.drive.jooq.db.DefaultCatalog;
import com.nextcont.drive.jooq.db.ecm_trans.tables.FastdfsFilerecord;
import com.nextcont.drive.jooq.db.ecm_trans.tables.Meqaupload;
import com.nextcont.drive.jooq.db.ecm_trans.tables.Transition;
import com.nextcont.drive.jooq.db.ecm_trans.tables.TransitionCallback;
import com.nextcont.drive.jooq.db.ecm_trans.tables.TransitionFile;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EcmTrans extends SchemaImpl {

    private static final long serialVersionUID = -95926217;

    /**
     * The reference instance of <code>ecm_trans</code>
     */
    public static final EcmTrans ECM_TRANS = new EcmTrans();

    /**
     * The table <code>ecm_trans.fastdfs_fileRecord</code>.
     */
    public final FastdfsFilerecord FASTDFS_FILERECORD = com.nextcont.drive.jooq.db.ecm_trans.tables.FastdfsFilerecord.FASTDFS_FILERECORD;

    /**
     * The table <code>ecm_trans.meqaupload</code>.
     */
    public final Meqaupload MEQAUPLOAD = com.nextcont.drive.jooq.db.ecm_trans.tables.Meqaupload.MEQAUPLOAD;

    /**
     * The table <code>ecm_trans.transition</code>.
     */
    public final Transition TRANSITION = com.nextcont.drive.jooq.db.ecm_trans.tables.Transition.TRANSITION;

    /**
     * The table <code>ecm_trans.transition_callback</code>.
     */
    public final TransitionCallback TRANSITION_CALLBACK = com.nextcont.drive.jooq.db.ecm_trans.tables.TransitionCallback.TRANSITION_CALLBACK;

    /**
     * The table <code>ecm_trans.transition_file</code>.
     */
    public final TransitionFile TRANSITION_FILE = com.nextcont.drive.jooq.db.ecm_trans.tables.TransitionFile.TRANSITION_FILE;

    /**
     * No further instances allowed
     */
    private EcmTrans() {
        super("ecm_trans", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            FastdfsFilerecord.FASTDFS_FILERECORD,
            Meqaupload.MEQAUPLOAD,
            Transition.TRANSITION,
            TransitionCallback.TRANSITION_CALLBACK,
            TransitionFile.TRANSITION_FILE);
    }
}
