/*
 * This file is generated by jOOQ.
*/
package com.nextcont.drive.jooq.db.mysql.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * Column privileges
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ColumnsPriv implements Serializable {

    private static final long serialVersionUID = -906414636;

    private String    host;
    private String    db;
    private String    user;
    private String    tableName;
    private String    columnName;
    private Timestamp timestamp;
    private String    columnPriv;

    public ColumnsPriv() {}

    public ColumnsPriv(ColumnsPriv value) {
        this.host = value.host;
        this.db = value.db;
        this.user = value.user;
        this.tableName = value.tableName;
        this.columnName = value.columnName;
        this.timestamp = value.timestamp;
        this.columnPriv = value.columnPriv;
    }

    public ColumnsPriv(
        String    host,
        String    db,
        String    user,
        String    tableName,
        String    columnName,
        Timestamp timestamp,
        String    columnPriv
    ) {
        this.host = host;
        this.db = db;
        this.user = user;
        this.tableName = tableName;
        this.columnName = columnName;
        this.timestamp = timestamp;
        this.columnPriv = columnPriv;
    }

    public String getHost() {
        return this.host;
    }

    public void setHost(String host) {
        this.host = host;
    }

    public String getDb() {
        return this.db;
    }

    public void setDb(String db) {
        this.db = db;
    }

    public String getUser() {
        return this.user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public String getTableName() {
        return this.tableName;
    }

    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    public String getColumnName() {
        return this.columnName;
    }

    public void setColumnName(String columnName) {
        this.columnName = columnName;
    }

    public Timestamp getTimestamp() {
        return this.timestamp;
    }

    public void setTimestamp(Timestamp timestamp) {
        this.timestamp = timestamp;
    }

    public String getColumnPriv() {
        return this.columnPriv;
    }

    public void setColumnPriv(String columnPriv) {
        this.columnPriv = columnPriv;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ColumnsPriv (");

        sb.append(host);
        sb.append(", ").append(db);
        sb.append(", ").append(user);
        sb.append(", ").append(tableName);
        sb.append(", ").append(columnName);
        sb.append(", ").append(timestamp);
        sb.append(", ").append(columnPriv);

        sb.append(")");
        return sb.toString();
    }
}
