/*
 * This file is generated by jOOQ.
*/
package com.nextcont.drive.jooq.db.mysql.tables.pojos;


import com.nextcont.drive.jooq.db.mysql.enums.DbAlterPriv;
import com.nextcont.drive.jooq.db.mysql.enums.DbAlterRoutinePriv;
import com.nextcont.drive.jooq.db.mysql.enums.DbCreatePriv;
import com.nextcont.drive.jooq.db.mysql.enums.DbCreateRoutinePriv;
import com.nextcont.drive.jooq.db.mysql.enums.DbCreateTmpTablePriv;
import com.nextcont.drive.jooq.db.mysql.enums.DbCreateViewPriv;
import com.nextcont.drive.jooq.db.mysql.enums.DbDeletePriv;
import com.nextcont.drive.jooq.db.mysql.enums.DbDropPriv;
import com.nextcont.drive.jooq.db.mysql.enums.DbEventPriv;
import com.nextcont.drive.jooq.db.mysql.enums.DbExecutePriv;
import com.nextcont.drive.jooq.db.mysql.enums.DbGrantPriv;
import com.nextcont.drive.jooq.db.mysql.enums.DbIndexPriv;
import com.nextcont.drive.jooq.db.mysql.enums.DbInsertPriv;
import com.nextcont.drive.jooq.db.mysql.enums.DbLockTablesPriv;
import com.nextcont.drive.jooq.db.mysql.enums.DbReferencesPriv;
import com.nextcont.drive.jooq.db.mysql.enums.DbSelectPriv;
import com.nextcont.drive.jooq.db.mysql.enums.DbShowViewPriv;
import com.nextcont.drive.jooq.db.mysql.enums.DbTriggerPriv;
import com.nextcont.drive.jooq.db.mysql.enums.DbUpdatePriv;

import java.io.Serializable;

import javax.annotation.Generated;


/**
 * Database privileges
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Db implements Serializable {

    private static final long serialVersionUID = -1403288829;

    private String               host;
    private String               db;
    private String               user;
    private DbSelectPriv         selectPriv;
    private DbInsertPriv         insertPriv;
    private DbUpdatePriv         updatePriv;
    private DbDeletePriv         deletePriv;
    private DbCreatePriv         createPriv;
    private DbDropPriv           dropPriv;
    private DbGrantPriv          grantPriv;
    private DbReferencesPriv     referencesPriv;
    private DbIndexPriv          indexPriv;
    private DbAlterPriv          alterPriv;
    private DbCreateTmpTablePriv createTmpTablePriv;
    private DbLockTablesPriv     lockTablesPriv;
    private DbCreateViewPriv     createViewPriv;
    private DbShowViewPriv       showViewPriv;
    private DbCreateRoutinePriv  createRoutinePriv;
    private DbAlterRoutinePriv   alterRoutinePriv;
    private DbExecutePriv        executePriv;
    private DbEventPriv          eventPriv;
    private DbTriggerPriv        triggerPriv;

    public Db() {}

    public Db(Db value) {
        this.host = value.host;
        this.db = value.db;
        this.user = value.user;
        this.selectPriv = value.selectPriv;
        this.insertPriv = value.insertPriv;
        this.updatePriv = value.updatePriv;
        this.deletePriv = value.deletePriv;
        this.createPriv = value.createPriv;
        this.dropPriv = value.dropPriv;
        this.grantPriv = value.grantPriv;
        this.referencesPriv = value.referencesPriv;
        this.indexPriv = value.indexPriv;
        this.alterPriv = value.alterPriv;
        this.createTmpTablePriv = value.createTmpTablePriv;
        this.lockTablesPriv = value.lockTablesPriv;
        this.createViewPriv = value.createViewPriv;
        this.showViewPriv = value.showViewPriv;
        this.createRoutinePriv = value.createRoutinePriv;
        this.alterRoutinePriv = value.alterRoutinePriv;
        this.executePriv = value.executePriv;
        this.eventPriv = value.eventPriv;
        this.triggerPriv = value.triggerPriv;
    }

    public Db(
        String               host,
        String               db,
        String               user,
        DbSelectPriv         selectPriv,
        DbInsertPriv         insertPriv,
        DbUpdatePriv         updatePriv,
        DbDeletePriv         deletePriv,
        DbCreatePriv         createPriv,
        DbDropPriv           dropPriv,
        DbGrantPriv          grantPriv,
        DbReferencesPriv     referencesPriv,
        DbIndexPriv          indexPriv,
        DbAlterPriv          alterPriv,
        DbCreateTmpTablePriv createTmpTablePriv,
        DbLockTablesPriv     lockTablesPriv,
        DbCreateViewPriv     createViewPriv,
        DbShowViewPriv       showViewPriv,
        DbCreateRoutinePriv  createRoutinePriv,
        DbAlterRoutinePriv   alterRoutinePriv,
        DbExecutePriv        executePriv,
        DbEventPriv          eventPriv,
        DbTriggerPriv        triggerPriv
    ) {
        this.host = host;
        this.db = db;
        this.user = user;
        this.selectPriv = selectPriv;
        this.insertPriv = insertPriv;
        this.updatePriv = updatePriv;
        this.deletePriv = deletePriv;
        this.createPriv = createPriv;
        this.dropPriv = dropPriv;
        this.grantPriv = grantPriv;
        this.referencesPriv = referencesPriv;
        this.indexPriv = indexPriv;
        this.alterPriv = alterPriv;
        this.createTmpTablePriv = createTmpTablePriv;
        this.lockTablesPriv = lockTablesPriv;
        this.createViewPriv = createViewPriv;
        this.showViewPriv = showViewPriv;
        this.createRoutinePriv = createRoutinePriv;
        this.alterRoutinePriv = alterRoutinePriv;
        this.executePriv = executePriv;
        this.eventPriv = eventPriv;
        this.triggerPriv = triggerPriv;
    }

    public String getHost() {
        return this.host;
    }

    public void setHost(String host) {
        this.host = host;
    }

    public String getDb() {
        return this.db;
    }

    public void setDb(String db) {
        this.db = db;
    }

    public String getUser() {
        return this.user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public DbSelectPriv getSelectPriv() {
        return this.selectPriv;
    }

    public void setSelectPriv(DbSelectPriv selectPriv) {
        this.selectPriv = selectPriv;
    }

    public DbInsertPriv getInsertPriv() {
        return this.insertPriv;
    }

    public void setInsertPriv(DbInsertPriv insertPriv) {
        this.insertPriv = insertPriv;
    }

    public DbUpdatePriv getUpdatePriv() {
        return this.updatePriv;
    }

    public void setUpdatePriv(DbUpdatePriv updatePriv) {
        this.updatePriv = updatePriv;
    }

    public DbDeletePriv getDeletePriv() {
        return this.deletePriv;
    }

    public void setDeletePriv(DbDeletePriv deletePriv) {
        this.deletePriv = deletePriv;
    }

    public DbCreatePriv getCreatePriv() {
        return this.createPriv;
    }

    public void setCreatePriv(DbCreatePriv createPriv) {
        this.createPriv = createPriv;
    }

    public DbDropPriv getDropPriv() {
        return this.dropPriv;
    }

    public void setDropPriv(DbDropPriv dropPriv) {
        this.dropPriv = dropPriv;
    }

    public DbGrantPriv getGrantPriv() {
        return this.grantPriv;
    }

    public void setGrantPriv(DbGrantPriv grantPriv) {
        this.grantPriv = grantPriv;
    }

    public DbReferencesPriv getReferencesPriv() {
        return this.referencesPriv;
    }

    public void setReferencesPriv(DbReferencesPriv referencesPriv) {
        this.referencesPriv = referencesPriv;
    }

    public DbIndexPriv getIndexPriv() {
        return this.indexPriv;
    }

    public void setIndexPriv(DbIndexPriv indexPriv) {
        this.indexPriv = indexPriv;
    }

    public DbAlterPriv getAlterPriv() {
        return this.alterPriv;
    }

    public void setAlterPriv(DbAlterPriv alterPriv) {
        this.alterPriv = alterPriv;
    }

    public DbCreateTmpTablePriv getCreateTmpTablePriv() {
        return this.createTmpTablePriv;
    }

    public void setCreateTmpTablePriv(DbCreateTmpTablePriv createTmpTablePriv) {
        this.createTmpTablePriv = createTmpTablePriv;
    }

    public DbLockTablesPriv getLockTablesPriv() {
        return this.lockTablesPriv;
    }

    public void setLockTablesPriv(DbLockTablesPriv lockTablesPriv) {
        this.lockTablesPriv = lockTablesPriv;
    }

    public DbCreateViewPriv getCreateViewPriv() {
        return this.createViewPriv;
    }

    public void setCreateViewPriv(DbCreateViewPriv createViewPriv) {
        this.createViewPriv = createViewPriv;
    }

    public DbShowViewPriv getShowViewPriv() {
        return this.showViewPriv;
    }

    public void setShowViewPriv(DbShowViewPriv showViewPriv) {
        this.showViewPriv = showViewPriv;
    }

    public DbCreateRoutinePriv getCreateRoutinePriv() {
        return this.createRoutinePriv;
    }

    public void setCreateRoutinePriv(DbCreateRoutinePriv createRoutinePriv) {
        this.createRoutinePriv = createRoutinePriv;
    }

    public DbAlterRoutinePriv getAlterRoutinePriv() {
        return this.alterRoutinePriv;
    }

    public void setAlterRoutinePriv(DbAlterRoutinePriv alterRoutinePriv) {
        this.alterRoutinePriv = alterRoutinePriv;
    }

    public DbExecutePriv getExecutePriv() {
        return this.executePriv;
    }

    public void setExecutePriv(DbExecutePriv executePriv) {
        this.executePriv = executePriv;
    }

    public DbEventPriv getEventPriv() {
        return this.eventPriv;
    }

    public void setEventPriv(DbEventPriv eventPriv) {
        this.eventPriv = eventPriv;
    }

    public DbTriggerPriv getTriggerPriv() {
        return this.triggerPriv;
    }

    public void setTriggerPriv(DbTriggerPriv triggerPriv) {
        this.triggerPriv = triggerPriv;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Db (");

        sb.append(host);
        sb.append(", ").append(db);
        sb.append(", ").append(user);
        sb.append(", ").append(selectPriv);
        sb.append(", ").append(insertPriv);
        sb.append(", ").append(updatePriv);
        sb.append(", ").append(deletePriv);
        sb.append(", ").append(createPriv);
        sb.append(", ").append(dropPriv);
        sb.append(", ").append(grantPriv);
        sb.append(", ").append(referencesPriv);
        sb.append(", ").append(indexPriv);
        sb.append(", ").append(alterPriv);
        sb.append(", ").append(createTmpTablePriv);
        sb.append(", ").append(lockTablesPriv);
        sb.append(", ").append(createViewPriv);
        sb.append(", ").append(showViewPriv);
        sb.append(", ").append(createRoutinePriv);
        sb.append(", ").append(alterRoutinePriv);
        sb.append(", ").append(executePriv);
        sb.append(", ").append(eventPriv);
        sb.append(", ").append(triggerPriv);

        sb.append(")");
        return sb.toString();
    }
}
