/*
 * This file is generated by jOOQ.
*/
package com.nextcont.drive.jooq.db.mysql.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * help keywords
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HelpKeyword implements Serializable {

    private static final long serialVersionUID = -417258066;

    private UInteger helpKeywordId;
    private String   name;

    public HelpKeyword() {}

    public HelpKeyword(HelpKeyword value) {
        this.helpKeywordId = value.helpKeywordId;
        this.name = value.name;
    }

    public HelpKeyword(
        UInteger helpKeywordId,
        String   name
    ) {
        this.helpKeywordId = helpKeywordId;
        this.name = name;
    }

    public UInteger getHelpKeywordId() {
        return this.helpKeywordId;
    }

    public void setHelpKeywordId(UInteger helpKeywordId) {
        this.helpKeywordId = helpKeywordId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("HelpKeyword (");

        sb.append(helpKeywordId);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
