/*
 * This file is generated by jOOQ.
*/
package com.nextcont.drive.jooq.db.mysql.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.UShort;


/**
 * help categories
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HelpCategory implements Serializable {

    private static final long serialVersionUID = -2091463927;

    private UShort helpCategoryId;
    private String name;
    private UShort parentCategoryId;
    private String url;

    public HelpCategory() {}

    public HelpCategory(HelpCategory value) {
        this.helpCategoryId = value.helpCategoryId;
        this.name = value.name;
        this.parentCategoryId = value.parentCategoryId;
        this.url = value.url;
    }

    public HelpCategory(
        UShort helpCategoryId,
        String name,
        UShort parentCategoryId,
        String url
    ) {
        this.helpCategoryId = helpCategoryId;
        this.name = name;
        this.parentCategoryId = parentCategoryId;
        this.url = url;
    }

    public UShort getHelpCategoryId() {
        return this.helpCategoryId;
    }

    public void setHelpCategoryId(UShort helpCategoryId) {
        this.helpCategoryId = helpCategoryId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public UShort getParentCategoryId() {
        return this.parentCategoryId;
    }

    public void setParentCategoryId(UShort parentCategoryId) {
        this.parentCategoryId = parentCategoryId;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("HelpCategory (");

        sb.append(helpCategoryId);
        sb.append(", ").append(name);
        sb.append(", ").append(parentCategoryId);
        sb.append(", ").append(url);

        sb.append(")");
        return sb.toString();
    }
}
