/*
 * This file is generated by jOOQ.
*/
package com.nextcont.drive.jooq.db.mysql.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.UInteger;
import org.jooq.types.UShort;


/**
 * help topics
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HelpTopic implements Serializable {

    private static final long serialVersionUID = -994868298;

    private UInteger helpTopicId;
    private String   name;
    private UShort   helpCategoryId;
    private String   description;
    private String   example;
    private String   url;

    public HelpTopic() {}

    public HelpTopic(HelpTopic value) {
        this.helpTopicId = value.helpTopicId;
        this.name = value.name;
        this.helpCategoryId = value.helpCategoryId;
        this.description = value.description;
        this.example = value.example;
        this.url = value.url;
    }

    public HelpTopic(
        UInteger helpTopicId,
        String   name,
        UShort   helpCategoryId,
        String   description,
        String   example,
        String   url
    ) {
        this.helpTopicId = helpTopicId;
        this.name = name;
        this.helpCategoryId = helpCategoryId;
        this.description = description;
        this.example = example;
        this.url = url;
    }

    public UInteger getHelpTopicId() {
        return this.helpTopicId;
    }

    public void setHelpTopicId(UInteger helpTopicId) {
        this.helpTopicId = helpTopicId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public UShort getHelpCategoryId() {
        return this.helpCategoryId;
    }

    public void setHelpCategoryId(UShort helpCategoryId) {
        this.helpCategoryId = helpCategoryId;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getExample() {
        return this.example;
    }

    public void setExample(String example) {
        this.example = example;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("HelpTopic (");

        sb.append(helpTopicId);
        sb.append(", ").append(name);
        sb.append(", ").append(helpCategoryId);
        sb.append(", ").append(description);
        sb.append(", ").append(example);
        sb.append(", ").append(url);

        sb.append(")");
        return sb.toString();
    }
}
