/*
 * This file is generated by jOOQ.
*/
package com.nextcont.drive.jooq.db.mysql.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NdbBinlogIndex implements Serializable {

    private static final long serialVersionUID = -917667355;

    private ULong  position;
    private String file;
    private ULong  epoch;
    private ULong  inserts;
    private ULong  updates;
    private ULong  deletes;
    private ULong  schemaops;

    public NdbBinlogIndex() {}

    public NdbBinlogIndex(NdbBinlogIndex value) {
        this.position = value.position;
        this.file = value.file;
        this.epoch = value.epoch;
        this.inserts = value.inserts;
        this.updates = value.updates;
        this.deletes = value.deletes;
        this.schemaops = value.schemaops;
    }

    public NdbBinlogIndex(
        ULong  position,
        String file,
        ULong  epoch,
        ULong  inserts,
        ULong  updates,
        ULong  deletes,
        ULong  schemaops
    ) {
        this.position = position;
        this.file = file;
        this.epoch = epoch;
        this.inserts = inserts;
        this.updates = updates;
        this.deletes = deletes;
        this.schemaops = schemaops;
    }

    public ULong getPosition() {
        return this.position;
    }

    public void setPosition(ULong position) {
        this.position = position;
    }

    public String getFile() {
        return this.file;
    }

    public void setFile(String file) {
        this.file = file;
    }

    public ULong getEpoch() {
        return this.epoch;
    }

    public void setEpoch(ULong epoch) {
        this.epoch = epoch;
    }

    public ULong getInserts() {
        return this.inserts;
    }

    public void setInserts(ULong inserts) {
        this.inserts = inserts;
    }

    public ULong getUpdates() {
        return this.updates;
    }

    public void setUpdates(ULong updates) {
        this.updates = updates;
    }

    public ULong getDeletes() {
        return this.deletes;
    }

    public void setDeletes(ULong deletes) {
        this.deletes = deletes;
    }

    public ULong getSchemaops() {
        return this.schemaops;
    }

    public void setSchemaops(ULong schemaops) {
        this.schemaops = schemaops;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("NdbBinlogIndex (");

        sb.append(position);
        sb.append(", ").append(file);
        sb.append(", ").append(epoch);
        sb.append(", ").append(inserts);
        sb.append(", ").append(updates);
        sb.append(", ").append(deletes);
        sb.append(", ").append(schemaops);

        sb.append(")");
        return sb.toString();
    }
}
