/*
 * This file is generated by jOOQ.
*/
package com.nextcont.drive.jooq.db.mysql.tables.pojos;


import com.nextcont.drive.jooq.db.mysql.enums.ProcsPrivRoutineType;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * Procedure privileges
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProcsPriv implements Serializable {

    private static final long serialVersionUID = 610150268;

    private String               host;
    private String               db;
    private String               user;
    private String               routineName;
    private ProcsPrivRoutineType routineType;
    private String               grantor;
    private String               procPriv;
    private Timestamp            timestamp;

    public ProcsPriv() {}

    public ProcsPriv(ProcsPriv value) {
        this.host = value.host;
        this.db = value.db;
        this.user = value.user;
        this.routineName = value.routineName;
        this.routineType = value.routineType;
        this.grantor = value.grantor;
        this.procPriv = value.procPriv;
        this.timestamp = value.timestamp;
    }

    public ProcsPriv(
        String               host,
        String               db,
        String               user,
        String               routineName,
        ProcsPrivRoutineType routineType,
        String               grantor,
        String               procPriv,
        Timestamp            timestamp
    ) {
        this.host = host;
        this.db = db;
        this.user = user;
        this.routineName = routineName;
        this.routineType = routineType;
        this.grantor = grantor;
        this.procPriv = procPriv;
        this.timestamp = timestamp;
    }

    public String getHost() {
        return this.host;
    }

    public void setHost(String host) {
        this.host = host;
    }

    public String getDb() {
        return this.db;
    }

    public void setDb(String db) {
        this.db = db;
    }

    public String getUser() {
        return this.user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public String getRoutineName() {
        return this.routineName;
    }

    public void setRoutineName(String routineName) {
        this.routineName = routineName;
    }

    public ProcsPrivRoutineType getRoutineType() {
        return this.routineType;
    }

    public void setRoutineType(ProcsPrivRoutineType routineType) {
        this.routineType = routineType;
    }

    public String getGrantor() {
        return this.grantor;
    }

    public void setGrantor(String grantor) {
        this.grantor = grantor;
    }

    public String getProcPriv() {
        return this.procPriv;
    }

    public void setProcPriv(String procPriv) {
        this.procPriv = procPriv;
    }

    public Timestamp getTimestamp() {
        return this.timestamp;
    }

    public void setTimestamp(Timestamp timestamp) {
        this.timestamp = timestamp;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProcsPriv (");

        sb.append(host);
        sb.append(", ").append(db);
        sb.append(", ").append(user);
        sb.append(", ").append(routineName);
        sb.append(", ").append(routineType);
        sb.append(", ").append(grantor);
        sb.append(", ").append(procPriv);
        sb.append(", ").append(timestamp);

        sb.append(")");
        return sb.toString();
    }
}
