/*
 * This file is generated by jOOQ.
*/
package com.nextcont.drive.jooq.db.mysql.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.UByte;
import org.jooq.types.UInteger;


/**
 * Time zone transition types
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TimeZoneTransitionType implements Serializable {

    private static final long serialVersionUID = -1832340249;

    private UInteger timeZoneId;
    private UInteger transitionTypeId;
    private Integer  offset;
    private UByte    isDst;
    private String   abbreviation;

    public TimeZoneTransitionType() {}

    public TimeZoneTransitionType(TimeZoneTransitionType value) {
        this.timeZoneId = value.timeZoneId;
        this.transitionTypeId = value.transitionTypeId;
        this.offset = value.offset;
        this.isDst = value.isDst;
        this.abbreviation = value.abbreviation;
    }

    public TimeZoneTransitionType(
        UInteger timeZoneId,
        UInteger transitionTypeId,
        Integer  offset,
        UByte    isDst,
        String   abbreviation
    ) {
        this.timeZoneId = timeZoneId;
        this.transitionTypeId = transitionTypeId;
        this.offset = offset;
        this.isDst = isDst;
        this.abbreviation = abbreviation;
    }

    public UInteger getTimeZoneId() {
        return this.timeZoneId;
    }

    public void setTimeZoneId(UInteger timeZoneId) {
        this.timeZoneId = timeZoneId;
    }

    public UInteger getTransitionTypeId() {
        return this.transitionTypeId;
    }

    public void setTransitionTypeId(UInteger transitionTypeId) {
        this.transitionTypeId = transitionTypeId;
    }

    public Integer getOffset() {
        return this.offset;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public UByte getIsDst() {
        return this.isDst;
    }

    public void setIsDst(UByte isDst) {
        this.isDst = isDst;
    }

    public String getAbbreviation() {
        return this.abbreviation;
    }

    public void setAbbreviation(String abbreviation) {
        this.abbreviation = abbreviation;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TimeZoneTransitionType (");

        sb.append(timeZoneId);
        sb.append(", ").append(transitionTypeId);
        sb.append(", ").append(offset);
        sb.append(", ").append(isDst);
        sb.append(", ").append(abbreviation);

        sb.append(")");
        return sb.toString();
    }
}
