/*
 * This file is generated by jOOQ.
*/
package com.nextcont.drive.jooq.db.mysql.tables.pojos;


import com.nextcont.drive.jooq.db.mysql.enums.TimeZoneUseLeapSeconds;

import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * Time zones
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TimeZone implements Serializable {

    private static final long serialVersionUID = 1881625203;

    private UInteger               timeZoneId;
    private TimeZoneUseLeapSeconds useLeapSeconds;

    public TimeZone() {}

    public TimeZone(TimeZone value) {
        this.timeZoneId = value.timeZoneId;
        this.useLeapSeconds = value.useLeapSeconds;
    }

    public TimeZone(
        UInteger               timeZoneId,
        TimeZoneUseLeapSeconds useLeapSeconds
    ) {
        this.timeZoneId = timeZoneId;
        this.useLeapSeconds = useLeapSeconds;
    }

    public UInteger getTimeZoneId() {
        return this.timeZoneId;
    }

    public void setTimeZoneId(UInteger timeZoneId) {
        this.timeZoneId = timeZoneId;
    }

    public TimeZoneUseLeapSeconds getUseLeapSeconds() {
        return this.useLeapSeconds;
    }

    public void setUseLeapSeconds(TimeZoneUseLeapSeconds useLeapSeconds) {
        this.useLeapSeconds = useLeapSeconds;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TimeZone (");

        sb.append(timeZoneId);
        sb.append(", ").append(useLeapSeconds);

        sb.append(")");
        return sb.toString();
    }
}
