/*
 * This file is generated by jOOQ.
*/
package com.nextcont.drive.jooq.db.mysql.tables.pojos;


import com.nextcont.drive.jooq.db.mysql.enums.UserAlterPriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserAlterRoutinePriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserCreatePriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserCreateRoutinePriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserCreateTmpTablePriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserCreateUserPriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserCreateViewPriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserDeletePriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserDropPriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserEventPriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserExecutePriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserFilePriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserGrantPriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserIndexPriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserInsertPriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserLockTablesPriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserProcessPriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserReferencesPriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserReloadPriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserReplClientPriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserReplSlavePriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserSelectPriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserShowDbPriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserShowViewPriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserShutdownPriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserSslType;
import com.nextcont.drive.jooq.db.mysql.enums.UserSuperPriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserTriggerPriv;
import com.nextcont.drive.jooq.db.mysql.enums.UserUpdatePriv;

import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * Users and global privileges
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = 925659750;

    private String                 host;
    private String                 user;
    private String                 password;
    private UserSelectPriv         selectPriv;
    private UserInsertPriv         insertPriv;
    private UserUpdatePriv         updatePriv;
    private UserDeletePriv         deletePriv;
    private UserCreatePriv         createPriv;
    private UserDropPriv           dropPriv;
    private UserReloadPriv         reloadPriv;
    private UserShutdownPriv       shutdownPriv;
    private UserProcessPriv        processPriv;
    private UserFilePriv           filePriv;
    private UserGrantPriv          grantPriv;
    private UserReferencesPriv     referencesPriv;
    private UserIndexPriv          indexPriv;
    private UserAlterPriv          alterPriv;
    private UserShowDbPriv         showDbPriv;
    private UserSuperPriv          superPriv;
    private UserCreateTmpTablePriv createTmpTablePriv;
    private UserLockTablesPriv     lockTablesPriv;
    private UserExecutePriv        executePriv;
    private UserReplSlavePriv      replSlavePriv;
    private UserReplClientPriv     replClientPriv;
    private UserCreateViewPriv     createViewPriv;
    private UserShowViewPriv       showViewPriv;
    private UserCreateRoutinePriv  createRoutinePriv;
    private UserAlterRoutinePriv   alterRoutinePriv;
    private UserCreateUserPriv     createUserPriv;
    private UserEventPriv          eventPriv;
    private UserTriggerPriv        triggerPriv;
    private UserSslType            sslType;
    private byte[]                 sslCipher;
    private byte[]                 x509Issuer;
    private byte[]                 x509Subject;
    private UInteger               maxQuestions;
    private UInteger               maxUpdates;
    private UInteger               maxConnections;
    private UInteger               maxUserConnections;

    public User() {}

    public User(User value) {
        this.host = value.host;
        this.user = value.user;
        this.password = value.password;
        this.selectPriv = value.selectPriv;
        this.insertPriv = value.insertPriv;
        this.updatePriv = value.updatePriv;
        this.deletePriv = value.deletePriv;
        this.createPriv = value.createPriv;
        this.dropPriv = value.dropPriv;
        this.reloadPriv = value.reloadPriv;
        this.shutdownPriv = value.shutdownPriv;
        this.processPriv = value.processPriv;
        this.filePriv = value.filePriv;
        this.grantPriv = value.grantPriv;
        this.referencesPriv = value.referencesPriv;
        this.indexPriv = value.indexPriv;
        this.alterPriv = value.alterPriv;
        this.showDbPriv = value.showDbPriv;
        this.superPriv = value.superPriv;
        this.createTmpTablePriv = value.createTmpTablePriv;
        this.lockTablesPriv = value.lockTablesPriv;
        this.executePriv = value.executePriv;
        this.replSlavePriv = value.replSlavePriv;
        this.replClientPriv = value.replClientPriv;
        this.createViewPriv = value.createViewPriv;
        this.showViewPriv = value.showViewPriv;
        this.createRoutinePriv = value.createRoutinePriv;
        this.alterRoutinePriv = value.alterRoutinePriv;
        this.createUserPriv = value.createUserPriv;
        this.eventPriv = value.eventPriv;
        this.triggerPriv = value.triggerPriv;
        this.sslType = value.sslType;
        this.sslCipher = value.sslCipher;
        this.x509Issuer = value.x509Issuer;
        this.x509Subject = value.x509Subject;
        this.maxQuestions = value.maxQuestions;
        this.maxUpdates = value.maxUpdates;
        this.maxConnections = value.maxConnections;
        this.maxUserConnections = value.maxUserConnections;
    }

    public User(
        String                 host,
        String                 user,
        String                 password,
        UserSelectPriv         selectPriv,
        UserInsertPriv         insertPriv,
        UserUpdatePriv         updatePriv,
        UserDeletePriv         deletePriv,
        UserCreatePriv         createPriv,
        UserDropPriv           dropPriv,
        UserReloadPriv         reloadPriv,
        UserShutdownPriv       shutdownPriv,
        UserProcessPriv        processPriv,
        UserFilePriv           filePriv,
        UserGrantPriv          grantPriv,
        UserReferencesPriv     referencesPriv,
        UserIndexPriv          indexPriv,
        UserAlterPriv          alterPriv,
        UserShowDbPriv         showDbPriv,
        UserSuperPriv          superPriv,
        UserCreateTmpTablePriv createTmpTablePriv,
        UserLockTablesPriv     lockTablesPriv,
        UserExecutePriv        executePriv,
        UserReplSlavePriv      replSlavePriv,
        UserReplClientPriv     replClientPriv,
        UserCreateViewPriv     createViewPriv,
        UserShowViewPriv       showViewPriv,
        UserCreateRoutinePriv  createRoutinePriv,
        UserAlterRoutinePriv   alterRoutinePriv,
        UserCreateUserPriv     createUserPriv,
        UserEventPriv          eventPriv,
        UserTriggerPriv        triggerPriv,
        UserSslType            sslType,
        byte[]                 sslCipher,
        byte[]                 x509Issuer,
        byte[]                 x509Subject,
        UInteger               maxQuestions,
        UInteger               maxUpdates,
        UInteger               maxConnections,
        UInteger               maxUserConnections
    ) {
        this.host = host;
        this.user = user;
        this.password = password;
        this.selectPriv = selectPriv;
        this.insertPriv = insertPriv;
        this.updatePriv = updatePriv;
        this.deletePriv = deletePriv;
        this.createPriv = createPriv;
        this.dropPriv = dropPriv;
        this.reloadPriv = reloadPriv;
        this.shutdownPriv = shutdownPriv;
        this.processPriv = processPriv;
        this.filePriv = filePriv;
        this.grantPriv = grantPriv;
        this.referencesPriv = referencesPriv;
        this.indexPriv = indexPriv;
        this.alterPriv = alterPriv;
        this.showDbPriv = showDbPriv;
        this.superPriv = superPriv;
        this.createTmpTablePriv = createTmpTablePriv;
        this.lockTablesPriv = lockTablesPriv;
        this.executePriv = executePriv;
        this.replSlavePriv = replSlavePriv;
        this.replClientPriv = replClientPriv;
        this.createViewPriv = createViewPriv;
        this.showViewPriv = showViewPriv;
        this.createRoutinePriv = createRoutinePriv;
        this.alterRoutinePriv = alterRoutinePriv;
        this.createUserPriv = createUserPriv;
        this.eventPriv = eventPriv;
        this.triggerPriv = triggerPriv;
        this.sslType = sslType;
        this.sslCipher = sslCipher;
        this.x509Issuer = x509Issuer;
        this.x509Subject = x509Subject;
        this.maxQuestions = maxQuestions;
        this.maxUpdates = maxUpdates;
        this.maxConnections = maxConnections;
        this.maxUserConnections = maxUserConnections;
    }

    public String getHost() {
        return this.host;
    }

    public void setHost(String host) {
        this.host = host;
    }

    public String getUser() {
        return this.user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public UserSelectPriv getSelectPriv() {
        return this.selectPriv;
    }

    public void setSelectPriv(UserSelectPriv selectPriv) {
        this.selectPriv = selectPriv;
    }

    public UserInsertPriv getInsertPriv() {
        return this.insertPriv;
    }

    public void setInsertPriv(UserInsertPriv insertPriv) {
        this.insertPriv = insertPriv;
    }

    public UserUpdatePriv getUpdatePriv() {
        return this.updatePriv;
    }

    public void setUpdatePriv(UserUpdatePriv updatePriv) {
        this.updatePriv = updatePriv;
    }

    public UserDeletePriv getDeletePriv() {
        return this.deletePriv;
    }

    public void setDeletePriv(UserDeletePriv deletePriv) {
        this.deletePriv = deletePriv;
    }

    public UserCreatePriv getCreatePriv() {
        return this.createPriv;
    }

    public void setCreatePriv(UserCreatePriv createPriv) {
        this.createPriv = createPriv;
    }

    public UserDropPriv getDropPriv() {
        return this.dropPriv;
    }

    public void setDropPriv(UserDropPriv dropPriv) {
        this.dropPriv = dropPriv;
    }

    public UserReloadPriv getReloadPriv() {
        return this.reloadPriv;
    }

    public void setReloadPriv(UserReloadPriv reloadPriv) {
        this.reloadPriv = reloadPriv;
    }

    public UserShutdownPriv getShutdownPriv() {
        return this.shutdownPriv;
    }

    public void setShutdownPriv(UserShutdownPriv shutdownPriv) {
        this.shutdownPriv = shutdownPriv;
    }

    public UserProcessPriv getProcessPriv() {
        return this.processPriv;
    }

    public void setProcessPriv(UserProcessPriv processPriv) {
        this.processPriv = processPriv;
    }

    public UserFilePriv getFilePriv() {
        return this.filePriv;
    }

    public void setFilePriv(UserFilePriv filePriv) {
        this.filePriv = filePriv;
    }

    public UserGrantPriv getGrantPriv() {
        return this.grantPriv;
    }

    public void setGrantPriv(UserGrantPriv grantPriv) {
        this.grantPriv = grantPriv;
    }

    public UserReferencesPriv getReferencesPriv() {
        return this.referencesPriv;
    }

    public void setReferencesPriv(UserReferencesPriv referencesPriv) {
        this.referencesPriv = referencesPriv;
    }

    public UserIndexPriv getIndexPriv() {
        return this.indexPriv;
    }

    public void setIndexPriv(UserIndexPriv indexPriv) {
        this.indexPriv = indexPriv;
    }

    public UserAlterPriv getAlterPriv() {
        return this.alterPriv;
    }

    public void setAlterPriv(UserAlterPriv alterPriv) {
        this.alterPriv = alterPriv;
    }

    public UserShowDbPriv getShowDbPriv() {
        return this.showDbPriv;
    }

    public void setShowDbPriv(UserShowDbPriv showDbPriv) {
        this.showDbPriv = showDbPriv;
    }

    public UserSuperPriv getSuperPriv() {
        return this.superPriv;
    }

    public void setSuperPriv(UserSuperPriv superPriv) {
        this.superPriv = superPriv;
    }

    public UserCreateTmpTablePriv getCreateTmpTablePriv() {
        return this.createTmpTablePriv;
    }

    public void setCreateTmpTablePriv(UserCreateTmpTablePriv createTmpTablePriv) {
        this.createTmpTablePriv = createTmpTablePriv;
    }

    public UserLockTablesPriv getLockTablesPriv() {
        return this.lockTablesPriv;
    }

    public void setLockTablesPriv(UserLockTablesPriv lockTablesPriv) {
        this.lockTablesPriv = lockTablesPriv;
    }

    public UserExecutePriv getExecutePriv() {
        return this.executePriv;
    }

    public void setExecutePriv(UserExecutePriv executePriv) {
        this.executePriv = executePriv;
    }

    public UserReplSlavePriv getReplSlavePriv() {
        return this.replSlavePriv;
    }

    public void setReplSlavePriv(UserReplSlavePriv replSlavePriv) {
        this.replSlavePriv = replSlavePriv;
    }

    public UserReplClientPriv getReplClientPriv() {
        return this.replClientPriv;
    }

    public void setReplClientPriv(UserReplClientPriv replClientPriv) {
        this.replClientPriv = replClientPriv;
    }

    public UserCreateViewPriv getCreateViewPriv() {
        return this.createViewPriv;
    }

    public void setCreateViewPriv(UserCreateViewPriv createViewPriv) {
        this.createViewPriv = createViewPriv;
    }

    public UserShowViewPriv getShowViewPriv() {
        return this.showViewPriv;
    }

    public void setShowViewPriv(UserShowViewPriv showViewPriv) {
        this.showViewPriv = showViewPriv;
    }

    public UserCreateRoutinePriv getCreateRoutinePriv() {
        return this.createRoutinePriv;
    }

    public void setCreateRoutinePriv(UserCreateRoutinePriv createRoutinePriv) {
        this.createRoutinePriv = createRoutinePriv;
    }

    public UserAlterRoutinePriv getAlterRoutinePriv() {
        return this.alterRoutinePriv;
    }

    public void setAlterRoutinePriv(UserAlterRoutinePriv alterRoutinePriv) {
        this.alterRoutinePriv = alterRoutinePriv;
    }

    public UserCreateUserPriv getCreateUserPriv() {
        return this.createUserPriv;
    }

    public void setCreateUserPriv(UserCreateUserPriv createUserPriv) {
        this.createUserPriv = createUserPriv;
    }

    public UserEventPriv getEventPriv() {
        return this.eventPriv;
    }

    public void setEventPriv(UserEventPriv eventPriv) {
        this.eventPriv = eventPriv;
    }

    public UserTriggerPriv getTriggerPriv() {
        return this.triggerPriv;
    }

    public void setTriggerPriv(UserTriggerPriv triggerPriv) {
        this.triggerPriv = triggerPriv;
    }

    public UserSslType getSslType() {
        return this.sslType;
    }

    public void setSslType(UserSslType sslType) {
        this.sslType = sslType;
    }

    public byte[] getSslCipher() {
        return this.sslCipher;
    }

    public void setSslCipher(byte... sslCipher) {
        this.sslCipher = sslCipher;
    }

    public byte[] getX509Issuer() {
        return this.x509Issuer;
    }

    public void setX509Issuer(byte... x509Issuer) {
        this.x509Issuer = x509Issuer;
    }

    public byte[] getX509Subject() {
        return this.x509Subject;
    }

    public void setX509Subject(byte... x509Subject) {
        this.x509Subject = x509Subject;
    }

    public UInteger getMaxQuestions() {
        return this.maxQuestions;
    }

    public void setMaxQuestions(UInteger maxQuestions) {
        this.maxQuestions = maxQuestions;
    }

    public UInteger getMaxUpdates() {
        return this.maxUpdates;
    }

    public void setMaxUpdates(UInteger maxUpdates) {
        this.maxUpdates = maxUpdates;
    }

    public UInteger getMaxConnections() {
        return this.maxConnections;
    }

    public void setMaxConnections(UInteger maxConnections) {
        this.maxConnections = maxConnections;
    }

    public UInteger getMaxUserConnections() {
        return this.maxUserConnections;
    }

    public void setMaxUserConnections(UInteger maxUserConnections) {
        this.maxUserConnections = maxUserConnections;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(host);
        sb.append(", ").append(user);
        sb.append(", ").append(password);
        sb.append(", ").append(selectPriv);
        sb.append(", ").append(insertPriv);
        sb.append(", ").append(updatePriv);
        sb.append(", ").append(deletePriv);
        sb.append(", ").append(createPriv);
        sb.append(", ").append(dropPriv);
        sb.append(", ").append(reloadPriv);
        sb.append(", ").append(shutdownPriv);
        sb.append(", ").append(processPriv);
        sb.append(", ").append(filePriv);
        sb.append(", ").append(grantPriv);
        sb.append(", ").append(referencesPriv);
        sb.append(", ").append(indexPriv);
        sb.append(", ").append(alterPriv);
        sb.append(", ").append(showDbPriv);
        sb.append(", ").append(superPriv);
        sb.append(", ").append(createTmpTablePriv);
        sb.append(", ").append(lockTablesPriv);
        sb.append(", ").append(executePriv);
        sb.append(", ").append(replSlavePriv);
        sb.append(", ").append(replClientPriv);
        sb.append(", ").append(createViewPriv);
        sb.append(", ").append(showViewPriv);
        sb.append(", ").append(createRoutinePriv);
        sb.append(", ").append(alterRoutinePriv);
        sb.append(", ").append(createUserPriv);
        sb.append(", ").append(eventPriv);
        sb.append(", ").append(triggerPriv);
        sb.append(", ").append(sslType);
        sb.append(", ").append("[binary...]");
        sb.append(", ").append("[binary...]");
        sb.append(", ").append("[binary...]");
        sb.append(", ").append(maxQuestions);
        sb.append(", ").append(maxUpdates);
        sb.append(", ").append(maxConnections);
        sb.append(", ").append(maxUserConnections);

        sb.append(")");
        return sb.toString();
    }
}
