/*
 * This file is generated by jOOQ.
*/
package com.nextcont.drive.jooq.db.ecm_trans.tables.records;


import com.nextcont.drive.jooq.db.ecm_trans.tables.FastdfsFilerecord;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FastdfsFilerecordRecord extends UpdatableRecordImpl<FastdfsFilerecordRecord> implements Record11<String, String, String, String, String, Timestamp, Timestamp, String, String, String, String> {

    private static final long serialVersionUID = 2112196485;

    /**
     * Setter for <code>ecm_trans.fastdfs_fileRecord.globalId</code>.
     */
    public void setGlobalid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>ecm_trans.fastdfs_fileRecord.globalId</code>.
     */
    public String getGlobalid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>ecm_trans.fastdfs_fileRecord.fid</code>.
     */
    public void setFid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>ecm_trans.fastdfs_fileRecord.fid</code>.
     */
    public String getFid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ecm_trans.fastdfs_fileRecord.groupName</code>.
     */
    public void setGroupname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>ecm_trans.fastdfs_fileRecord.groupName</code>.
     */
    public String getGroupname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ecm_trans.fastdfs_fileRecord.fileName</code>.
     */
    public void setFilename(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>ecm_trans.fastdfs_fileRecord.fileName</code>.
     */
    public String getFilename() {
        return (String) get(3);
    }

    /**
     * Setter for <code>ecm_trans.fastdfs_fileRecord.extensionsName</code>.
     */
    public void setExtensionsname(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>ecm_trans.fastdfs_fileRecord.extensionsName</code>.
     */
    public String getExtensionsname() {
        return (String) get(4);
    }

    /**
     * Setter for <code>ecm_trans.fastdfs_fileRecord.createTime</code>.
     */
    public void setCreatetime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>ecm_trans.fastdfs_fileRecord.createTime</code>.
     */
    public Timestamp getCreatetime() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>ecm_trans.fastdfs_fileRecord.updateTime</code>.
     */
    public void setUpdatetime(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>ecm_trans.fastdfs_fileRecord.updateTime</code>.
     */
    public Timestamp getUpdatetime() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>ecm_trans.fastdfs_fileRecord.httpEncoding</code>.
     */
    public void setHttpencoding(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>ecm_trans.fastdfs_fileRecord.httpEncoding</code>.
     */
    public String getHttpencoding() {
        return (String) get(7);
    }

    /**
     * Setter for <code>ecm_trans.fastdfs_fileRecord.fsRawValue</code>.
     */
    public void setFsrawvalue(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>ecm_trans.fastdfs_fileRecord.fsRawValue</code>.
     */
    public String getFsrawvalue() {
        return (String) get(8);
    }

    /**
     * Setter for <code>ecm_trans.fastdfs_fileRecord.path</code>.
     */
    public void setPath(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>ecm_trans.fastdfs_fileRecord.path</code>.
     */
    public String getPath() {
        return (String) get(9);
    }

    /**
     * Setter for <code>ecm_trans.fastdfs_fileRecord.mimeType</code>.
     */
    public void setMimetype(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>ecm_trans.fastdfs_fileRecord.mimeType</code>.
     */
    public String getMimetype() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<String, String, String, String, String, Timestamp, Timestamp, String, String, String, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<String, String, String, String, String, Timestamp, Timestamp, String, String, String, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return FastdfsFilerecord.FASTDFS_FILERECORD.GLOBALID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return FastdfsFilerecord.FASTDFS_FILERECORD.FID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return FastdfsFilerecord.FASTDFS_FILERECORD.GROUPNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return FastdfsFilerecord.FASTDFS_FILERECORD.FILENAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return FastdfsFilerecord.FASTDFS_FILERECORD.EXTENSIONSNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return FastdfsFilerecord.FASTDFS_FILERECORD.CREATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return FastdfsFilerecord.FASTDFS_FILERECORD.UPDATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return FastdfsFilerecord.FASTDFS_FILERECORD.HTTPENCODING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return FastdfsFilerecord.FASTDFS_FILERECORD.FSRAWVALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return FastdfsFilerecord.FASTDFS_FILERECORD.PATH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return FastdfsFilerecord.FASTDFS_FILERECORD.MIMETYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getGlobalid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getFid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getGroupname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getFilename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getExtensionsname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getUpdatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getHttpencoding();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getFsrawvalue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getPath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getMimetype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FastdfsFilerecordRecord value1(String value) {
        setGlobalid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FastdfsFilerecordRecord value2(String value) {
        setFid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FastdfsFilerecordRecord value3(String value) {
        setGroupname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FastdfsFilerecordRecord value4(String value) {
        setFilename(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FastdfsFilerecordRecord value5(String value) {
        setExtensionsname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FastdfsFilerecordRecord value6(Timestamp value) {
        setCreatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FastdfsFilerecordRecord value7(Timestamp value) {
        setUpdatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FastdfsFilerecordRecord value8(String value) {
        setHttpencoding(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FastdfsFilerecordRecord value9(String value) {
        setFsrawvalue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FastdfsFilerecordRecord value10(String value) {
        setPath(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FastdfsFilerecordRecord value11(String value) {
        setMimetype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FastdfsFilerecordRecord values(String value1, String value2, String value3, String value4, String value5, Timestamp value6, Timestamp value7, String value8, String value9, String value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FastdfsFilerecordRecord
     */
    public FastdfsFilerecordRecord() {
        super(FastdfsFilerecord.FASTDFS_FILERECORD);
    }

    /**
     * Create a detached, initialised FastdfsFilerecordRecord
     */
    public FastdfsFilerecordRecord(String globalid, String fid, String groupname, String filename, String extensionsname, Timestamp createtime, Timestamp updatetime, String httpencoding, String fsrawvalue, String path, String mimetype) {
        super(FastdfsFilerecord.FASTDFS_FILERECORD);

        set(0, globalid);
        set(1, fid);
        set(2, groupname);
        set(3, filename);
        set(4, extensionsname);
        set(5, createtime);
        set(6, updatetime);
        set(7, httpencoding);
        set(8, fsrawvalue);
        set(9, path);
        set(10, mimetype);
    }
}
