/*
 * This file is generated by jOOQ.
*/
package com.nextcont.drive.jooq.db.ecm_trans.tables.records;


import com.nextcont.drive.jooq.db.ecm_trans.tables.Meqaupload;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MeqauploadRecord extends UpdatableRecordImpl<MeqauploadRecord> implements Record9<String, String, String, Integer, Integer, Timestamp, Timestamp, Integer, Integer> {

    private static final long serialVersionUID = 691460124;

    /**
     * Setter for <code>ecm_trans.meqaupload.globalId</code>.
     */
    public void setGlobalid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>ecm_trans.meqaupload.globalId</code>.
     */
    public String getGlobalid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>ecm_trans.meqaupload.filename</code>.
     */
    public void setFilename(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>ecm_trans.meqaupload.filename</code>.
     */
    public String getFilename() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ecm_trans.meqaupload.mimetype</code>.
     */
    public void setMimetype(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>ecm_trans.meqaupload.mimetype</code>.
     */
    public String getMimetype() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ecm_trans.meqaupload.contentlength</code>.
     */
    public void setContentlength(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>ecm_trans.meqaupload.contentlength</code>.
     */
    public Integer getContentlength() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>ecm_trans.meqaupload.shardsize</code>.
     */
    public void setShardsize(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>ecm_trans.meqaupload.shardsize</code>.
     */
    public Integer getShardsize() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>ecm_trans.meqaupload.createtime</code>.
     */
    public void setCreatetime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>ecm_trans.meqaupload.createtime</code>.
     */
    public Timestamp getCreatetime() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>ecm_trans.meqaupload.updatetime</code>.
     */
    public void setUpdatetime(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>ecm_trans.meqaupload.updatetime</code>.
     */
    public Timestamp getUpdatetime() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>ecm_trans.meqaupload.currentshard</code>.
     */
    public void setCurrentshard(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>ecm_trans.meqaupload.currentshard</code>.
     */
    public Integer getCurrentshard() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>ecm_trans.meqaupload.partfilesize</code>.
     */
    public void setPartfilesize(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>ecm_trans.meqaupload.partfilesize</code>.
     */
    public Integer getPartfilesize() {
        return (Integer) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, String, String, Integer, Integer, Timestamp, Timestamp, Integer, Integer> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, String, String, Integer, Integer, Timestamp, Timestamp, Integer, Integer> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Meqaupload.MEQAUPLOAD.GLOBALID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Meqaupload.MEQAUPLOAD.FILENAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Meqaupload.MEQAUPLOAD.MIMETYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Meqaupload.MEQAUPLOAD.CONTENTLENGTH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Meqaupload.MEQAUPLOAD.SHARDSIZE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Meqaupload.MEQAUPLOAD.CREATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Meqaupload.MEQAUPLOAD.UPDATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Meqaupload.MEQAUPLOAD.CURRENTSHARD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return Meqaupload.MEQAUPLOAD.PARTFILESIZE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getGlobalid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getFilename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getMimetype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getContentlength();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getShardsize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getUpdatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getCurrentshard();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getPartfilesize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MeqauploadRecord value1(String value) {
        setGlobalid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MeqauploadRecord value2(String value) {
        setFilename(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MeqauploadRecord value3(String value) {
        setMimetype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MeqauploadRecord value4(Integer value) {
        setContentlength(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MeqauploadRecord value5(Integer value) {
        setShardsize(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MeqauploadRecord value6(Timestamp value) {
        setCreatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MeqauploadRecord value7(Timestamp value) {
        setUpdatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MeqauploadRecord value8(Integer value) {
        setCurrentshard(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MeqauploadRecord value9(Integer value) {
        setPartfilesize(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MeqauploadRecord values(String value1, String value2, String value3, Integer value4, Integer value5, Timestamp value6, Timestamp value7, Integer value8, Integer value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MeqauploadRecord
     */
    public MeqauploadRecord() {
        super(Meqaupload.MEQAUPLOAD);
    }

    /**
     * Create a detached, initialised MeqauploadRecord
     */
    public MeqauploadRecord(String globalid, String filename, String mimetype, Integer contentlength, Integer shardsize, Timestamp createtime, Timestamp updatetime, Integer currentshard, Integer partfilesize) {
        super(Meqaupload.MEQAUPLOAD);

        set(0, globalid);
        set(1, filename);
        set(2, mimetype);
        set(3, contentlength);
        set(4, shardsize);
        set(5, createtime);
        set(6, updatetime);
        set(7, currentshard);
        set(8, partfilesize);
    }
}
