/*
 * This file is generated by jOOQ.
*/
package com.nextcont.drive.jooq.db.ecm_trans.tables.records;


import com.nextcont.drive.jooq.db.ecm_trans.tables.TransitionCallback;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransitionCallbackRecord extends TableRecordImpl<TransitionCallbackRecord> implements Record8<String, String, String, String, String, Timestamp, Byte, String> {

    private static final long serialVersionUID = 1087609226;

    /**
     * Setter for <code>ecm_trans.transition_callback.globalId</code>.
     */
    public void setGlobalid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>ecm_trans.transition_callback.globalId</code>.
     */
    public String getGlobalid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>ecm_trans.transition_callback.fileId</code>.
     */
    public void setFileid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>ecm_trans.transition_callback.fileId</code>.
     */
    public String getFileid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ecm_trans.transition_callback.status</code>.
     */
    public void setStatus(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>ecm_trans.transition_callback.status</code>.
     */
    public String getStatus() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ecm_trans.transition_callback.info</code>.
     */
    public void setInfo(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>ecm_trans.transition_callback.info</code>.
     */
    public String getInfo() {
        return (String) get(3);
    }

    /**
     * Setter for <code>ecm_trans.transition_callback.callbackUrl</code>.
     */
    public void setCallbackurl(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>ecm_trans.transition_callback.callbackUrl</code>.
     */
    public String getCallbackurl() {
        return (String) get(4);
    }

    /**
     * Setter for <code>ecm_trans.transition_callback.createTime</code>.
     */
    public void setCreatetime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>ecm_trans.transition_callback.createTime</code>.
     */
    public Timestamp getCreatetime() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>ecm_trans.transition_callback.aggregationStatus</code>. 聚合状态
     */
    public void setAggregationstatus(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>ecm_trans.transition_callback.aggregationStatus</code>. 聚合状态
     */
    public Byte getAggregationstatus() {
        return (Byte) get(6);
    }

    /**
     * Setter for <code>ecm_trans.transition_callback.iconLink</code>. 文件图标链接
     */
    public void setIconlink(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>ecm_trans.transition_callback.iconLink</code>. 文件图标链接
     */
    public String getIconlink() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, String, String, String, String, Timestamp, Byte, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, String, String, String, String, Timestamp, Byte, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return TransitionCallback.TRANSITION_CALLBACK.GLOBALID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TransitionCallback.TRANSITION_CALLBACK.FILEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TransitionCallback.TRANSITION_CALLBACK.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TransitionCallback.TRANSITION_CALLBACK.INFO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TransitionCallback.TRANSITION_CALLBACK.CALLBACKURL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return TransitionCallback.TRANSITION_CALLBACK.CREATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field7() {
        return TransitionCallback.TRANSITION_CALLBACK.AGGREGATIONSTATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return TransitionCallback.TRANSITION_CALLBACK.ICONLINK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getGlobalid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getFileid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getInfo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCallbackurl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value7() {
        return getAggregationstatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getIconlink();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransitionCallbackRecord value1(String value) {
        setGlobalid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransitionCallbackRecord value2(String value) {
        setFileid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransitionCallbackRecord value3(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransitionCallbackRecord value4(String value) {
        setInfo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransitionCallbackRecord value5(String value) {
        setCallbackurl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransitionCallbackRecord value6(Timestamp value) {
        setCreatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransitionCallbackRecord value7(Byte value) {
        setAggregationstatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransitionCallbackRecord value8(String value) {
        setIconlink(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransitionCallbackRecord values(String value1, String value2, String value3, String value4, String value5, Timestamp value6, Byte value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TransitionCallbackRecord
     */
    public TransitionCallbackRecord() {
        super(TransitionCallback.TRANSITION_CALLBACK);
    }

    /**
     * Create a detached, initialised TransitionCallbackRecord
     */
    public TransitionCallbackRecord(String globalid, String fileid, String status, String info, String callbackurl, Timestamp createtime, Byte aggregationstatus, String iconlink) {
        super(TransitionCallback.TRANSITION_CALLBACK);

        set(0, globalid);
        set(1, fileid);
        set(2, status);
        set(3, info);
        set(4, callbackurl);
        set(5, createtime);
        set(6, aggregationstatus);
        set(7, iconlink);
    }
}
