/*
 * This file is generated by jOOQ.
*/
package com.nextcont.drive.jooq.db.ecm_trans.tables.records;


import com.nextcont.drive.jooq.db.ecm_trans.tables.Transition;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransitionRecord extends UpdatableRecordImpl<TransitionRecord> implements Record17<String, Timestamp, String, String, String, Long, String, String, String, String, String, String, Integer, String, String, String, String> {

    private static final long serialVersionUID = -685687347;

    /**
     * Setter for <code>ecm_trans.transition.globalId</code>. 请求id
     */
    public void setGlobalid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>ecm_trans.transition.globalId</code>. 请求id
     */
    public String getGlobalid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>ecm_trans.transition.createdate</code>. 创建时间
     */
    public void setCreatedate(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>ecm_trans.transition.createdate</code>. 创建时间
     */
    public Timestamp getCreatedate() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>ecm_trans.transition.requesttype</code>. 请求类型:HTTP|WEBSOCKET
     */
    public void setRequesttype(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>ecm_trans.transition.requesttype</code>. 请求类型:HTTP|WEBSOCKET
     */
    public String getRequesttype() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ecm_trans.transition.clientid</code>. caller client id
     */
    public void setClientid(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>ecm_trans.transition.clientid</code>. caller client id
     */
    public String getClientid() {
        return (String) get(3);
    }

    /**
     * Setter for <code>ecm_trans.transition.filename</code>. 文件名称
     */
    public void setFilename(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>ecm_trans.transition.filename</code>. 文件名称
     */
    public String getFilename() {
        return (String) get(4);
    }

    /**
     * Setter for <code>ecm_trans.transition.length</code>. 文件长度
     */
    public void setLength(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>ecm_trans.transition.length</code>. 文件长度
     */
    public Long getLength() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>ecm_trans.transition.mimetype</code>. 文件mime-type
     */
    public void setMimetype(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>ecm_trans.transition.mimetype</code>. 文件mime-type
     */
    public String getMimetype() {
        return (String) get(6);
    }

    /**
     * Setter for <code>ecm_trans.transition.source</code>. 文件来源:HTTP URL|FTP|FILE UPLOAD|CHUNCKED FILE UPLOAD
     */
    public void setSource(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>ecm_trans.transition.source</code>. 文件来源:HTTP URL|FTP|FILE UPLOAD|CHUNCKED FILE UPLOAD
     */
    public String getSource() {
        return (String) get(7);
    }

    /**
     * Setter for <code>ecm_trans.transition.callbackurl</code>. 回调URL
     */
    public void setCallbackurl(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>ecm_trans.transition.callbackurl</code>. 回调URL
     */
    public String getCallbackurl() {
        return (String) get(8);
    }

    /**
     * Setter for <code>ecm_trans.transition.md5digest</code>. 文件的md5摘要
     */
    public void setMd5digest(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>ecm_trans.transition.md5digest</code>. 文件的md5摘要
     */
    public String getMd5digest() {
        return (String) get(9);
    }

    /**
     * Setter for <code>ecm_trans.transition.fileextension</code>.
     */
    public void setFileextension(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>ecm_trans.transition.fileextension</code>.
     */
    public String getFileextension() {
        return (String) get(10);
    }

    /**
     * Setter for <code>ecm_trans.transition.alijobid</code>. 阿里转码jobid
     */
    public void setAlijobid(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>ecm_trans.transition.alijobid</code>. 阿里转码jobid
     */
    public String getAlijobid() {
        return (String) get(11);
    }

    /**
     * Setter for <code>ecm_trans.transition.filesize</code>.
     */
    public void setFilesize(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>ecm_trans.transition.filesize</code>.
     */
    public Integer getFilesize() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>ecm_trans.transition.callbacktype</code>.
     */
    public void setCallbacktype(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>ecm_trans.transition.callbacktype</code>.
     */
    public String getCallbacktype() {
        return (String) get(13);
    }

    /**
     * Setter for <code>ecm_trans.transition.websocketsessionid</code>.
     */
    public void setWebsocketsessionid(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>ecm_trans.transition.websocketsessionid</code>.
     */
    public String getWebsocketsessionid() {
        return (String) get(14);
    }

    /**
     * Setter for <code>ecm_trans.transition.errormsg</code>.
     */
    public void setErrormsg(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>ecm_trans.transition.errormsg</code>.
     */
    public String getErrormsg() {
        return (String) get(15);
    }

    /**
     * Setter for <code>ecm_trans.transition.location</code>.
     */
    public void setLocation(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>ecm_trans.transition.location</code>.
     */
    public String getLocation() {
        return (String) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<String, Timestamp, String, String, String, Long, String, String, String, String, String, String, Integer, String, String, String, String> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<String, Timestamp, String, String, String, Long, String, String, String, String, String, String, Integer, String, String, String, String> valuesRow() {
        return (Row17) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Transition.TRANSITION.GLOBALID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return Transition.TRANSITION.CREATEDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Transition.TRANSITION.REQUESTTYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Transition.TRANSITION.CLIENTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Transition.TRANSITION.FILENAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return Transition.TRANSITION.LENGTH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Transition.TRANSITION.MIMETYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Transition.TRANSITION.SOURCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Transition.TRANSITION.CALLBACKURL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Transition.TRANSITION.MD5DIGEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Transition.TRANSITION.FILEEXTENSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Transition.TRANSITION.ALIJOBID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return Transition.TRANSITION.FILESIZE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return Transition.TRANSITION.CALLBACKTYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return Transition.TRANSITION.WEBSOCKETSESSIONID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return Transition.TRANSITION.ERRORMSG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field17() {
        return Transition.TRANSITION.LOCATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getGlobalid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getCreatedate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getRequesttype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getClientid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getFilename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getLength();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getMimetype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getSource();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getCallbackurl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getMd5digest();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getFileextension();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getAlijobid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getFilesize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getCallbacktype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getWebsocketsessionid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getErrormsg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value17() {
        return getLocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransitionRecord value1(String value) {
        setGlobalid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransitionRecord value2(Timestamp value) {
        setCreatedate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransitionRecord value3(String value) {
        setRequesttype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransitionRecord value4(String value) {
        setClientid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransitionRecord value5(String value) {
        setFilename(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransitionRecord value6(Long value) {
        setLength(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransitionRecord value7(String value) {
        setMimetype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransitionRecord value8(String value) {
        setSource(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransitionRecord value9(String value) {
        setCallbackurl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransitionRecord value10(String value) {
        setMd5digest(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransitionRecord value11(String value) {
        setFileextension(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransitionRecord value12(String value) {
        setAlijobid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransitionRecord value13(Integer value) {
        setFilesize(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransitionRecord value14(String value) {
        setCallbacktype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransitionRecord value15(String value) {
        setWebsocketsessionid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransitionRecord value16(String value) {
        setErrormsg(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransitionRecord value17(String value) {
        setLocation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransitionRecord values(String value1, Timestamp value2, String value3, String value4, String value5, Long value6, String value7, String value8, String value9, String value10, String value11, String value12, Integer value13, String value14, String value15, String value16, String value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TransitionRecord
     */
    public TransitionRecord() {
        super(Transition.TRANSITION);
    }

    /**
     * Create a detached, initialised TransitionRecord
     */
    public TransitionRecord(String globalid, Timestamp createdate, String requesttype, String clientid, String filename, Long length, String mimetype, String source, String callbackurl, String md5digest, String fileextension, String alijobid, Integer filesize, String callbacktype, String websocketsessionid, String errormsg, String location) {
        super(Transition.TRANSITION);

        set(0, globalid);
        set(1, createdate);
        set(2, requesttype);
        set(3, clientid);
        set(4, filename);
        set(5, length);
        set(6, mimetype);
        set(7, source);
        set(8, callbackurl);
        set(9, md5digest);
        set(10, fileextension);
        set(11, alijobid);
        set(12, filesize);
        set(13, callbacktype);
        set(14, websocketsessionid);
        set(15, errormsg);
        set(16, location);
    }
}
