/*
 * This file is generated by jOOQ.
*/
package com.nextcont.drive.jooq.db.mysql.tables;


import com.nextcont.drive.jooq.db.mysql.Keys;
import com.nextcont.drive.jooq.db.mysql.Mysql;
import com.nextcont.drive.jooq.db.mysql.enums.HostAlterPriv;
import com.nextcont.drive.jooq.db.mysql.enums.HostAlterRoutinePriv;
import com.nextcont.drive.jooq.db.mysql.enums.HostCreatePriv;
import com.nextcont.drive.jooq.db.mysql.enums.HostCreateRoutinePriv;
import com.nextcont.drive.jooq.db.mysql.enums.HostCreateTmpTablePriv;
import com.nextcont.drive.jooq.db.mysql.enums.HostCreateViewPriv;
import com.nextcont.drive.jooq.db.mysql.enums.HostDeletePriv;
import com.nextcont.drive.jooq.db.mysql.enums.HostDropPriv;
import com.nextcont.drive.jooq.db.mysql.enums.HostExecutePriv;
import com.nextcont.drive.jooq.db.mysql.enums.HostGrantPriv;
import com.nextcont.drive.jooq.db.mysql.enums.HostIndexPriv;
import com.nextcont.drive.jooq.db.mysql.enums.HostInsertPriv;
import com.nextcont.drive.jooq.db.mysql.enums.HostLockTablesPriv;
import com.nextcont.drive.jooq.db.mysql.enums.HostReferencesPriv;
import com.nextcont.drive.jooq.db.mysql.enums.HostSelectPriv;
import com.nextcont.drive.jooq.db.mysql.enums.HostShowViewPriv;
import com.nextcont.drive.jooq.db.mysql.enums.HostTriggerPriv;
import com.nextcont.drive.jooq.db.mysql.enums.HostUpdatePriv;
import com.nextcont.drive.jooq.db.mysql.tables.records.HostRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * Host privileges;  Merged with database privileges
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Host extends TableImpl<HostRecord> {

    private static final long serialVersionUID = 626343507;

    /**
     * The reference instance of <code>mysql.host</code>
     */
    public static final Host HOST = new Host();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HostRecord> getRecordType() {
        return HostRecord.class;
    }

    /**
     * The column <code>mysql.host.Host</code>.
     */
    public final TableField<HostRecord, String> HOST_ = createField("Host", org.jooq.impl.SQLDataType.CHAR.length(60).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.CHAR)), this, "");

    /**
     * The column <code>mysql.host.Db</code>.
     */
    public final TableField<HostRecord, String> DB = createField("Db", org.jooq.impl.SQLDataType.CHAR.length(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.CHAR)), this, "");

    /**
     * The column <code>mysql.host.Select_priv</code>.
     */
    public final TableField<HostRecord, HostSelectPriv> SELECT_PRIV = createField("Select_priv", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(com.nextcont.drive.jooq.db.mysql.enums.HostSelectPriv.class), this, "");

    /**
     * The column <code>mysql.host.Insert_priv</code>.
     */
    public final TableField<HostRecord, HostInsertPriv> INSERT_PRIV = createField("Insert_priv", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(com.nextcont.drive.jooq.db.mysql.enums.HostInsertPriv.class), this, "");

    /**
     * The column <code>mysql.host.Update_priv</code>.
     */
    public final TableField<HostRecord, HostUpdatePriv> UPDATE_PRIV = createField("Update_priv", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(com.nextcont.drive.jooq.db.mysql.enums.HostUpdatePriv.class), this, "");

    /**
     * The column <code>mysql.host.Delete_priv</code>.
     */
    public final TableField<HostRecord, HostDeletePriv> DELETE_PRIV = createField("Delete_priv", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(com.nextcont.drive.jooq.db.mysql.enums.HostDeletePriv.class), this, "");

    /**
     * The column <code>mysql.host.Create_priv</code>.
     */
    public final TableField<HostRecord, HostCreatePriv> CREATE_PRIV = createField("Create_priv", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(com.nextcont.drive.jooq.db.mysql.enums.HostCreatePriv.class), this, "");

    /**
     * The column <code>mysql.host.Drop_priv</code>.
     */
    public final TableField<HostRecord, HostDropPriv> DROP_PRIV = createField("Drop_priv", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(com.nextcont.drive.jooq.db.mysql.enums.HostDropPriv.class), this, "");

    /**
     * The column <code>mysql.host.Grant_priv</code>.
     */
    public final TableField<HostRecord, HostGrantPriv> GRANT_PRIV = createField("Grant_priv", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(com.nextcont.drive.jooq.db.mysql.enums.HostGrantPriv.class), this, "");

    /**
     * The column <code>mysql.host.References_priv</code>.
     */
    public final TableField<HostRecord, HostReferencesPriv> REFERENCES_PRIV = createField("References_priv", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(com.nextcont.drive.jooq.db.mysql.enums.HostReferencesPriv.class), this, "");

    /**
     * The column <code>mysql.host.Index_priv</code>.
     */
    public final TableField<HostRecord, HostIndexPriv> INDEX_PRIV = createField("Index_priv", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(com.nextcont.drive.jooq.db.mysql.enums.HostIndexPriv.class), this, "");

    /**
     * The column <code>mysql.host.Alter_priv</code>.
     */
    public final TableField<HostRecord, HostAlterPriv> ALTER_PRIV = createField("Alter_priv", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(com.nextcont.drive.jooq.db.mysql.enums.HostAlterPriv.class), this, "");

    /**
     * The column <code>mysql.host.Create_tmp_table_priv</code>.
     */
    public final TableField<HostRecord, HostCreateTmpTablePriv> CREATE_TMP_TABLE_PRIV = createField("Create_tmp_table_priv", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(com.nextcont.drive.jooq.db.mysql.enums.HostCreateTmpTablePriv.class), this, "");

    /**
     * The column <code>mysql.host.Lock_tables_priv</code>.
     */
    public final TableField<HostRecord, HostLockTablesPriv> LOCK_TABLES_PRIV = createField("Lock_tables_priv", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(com.nextcont.drive.jooq.db.mysql.enums.HostLockTablesPriv.class), this, "");

    /**
     * The column <code>mysql.host.Create_view_priv</code>.
     */
    public final TableField<HostRecord, HostCreateViewPriv> CREATE_VIEW_PRIV = createField("Create_view_priv", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(com.nextcont.drive.jooq.db.mysql.enums.HostCreateViewPriv.class), this, "");

    /**
     * The column <code>mysql.host.Show_view_priv</code>.
     */
    public final TableField<HostRecord, HostShowViewPriv> SHOW_VIEW_PRIV = createField("Show_view_priv", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(com.nextcont.drive.jooq.db.mysql.enums.HostShowViewPriv.class), this, "");

    /**
     * The column <code>mysql.host.Create_routine_priv</code>.
     */
    public final TableField<HostRecord, HostCreateRoutinePriv> CREATE_ROUTINE_PRIV = createField("Create_routine_priv", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(com.nextcont.drive.jooq.db.mysql.enums.HostCreateRoutinePriv.class), this, "");

    /**
     * The column <code>mysql.host.Alter_routine_priv</code>.
     */
    public final TableField<HostRecord, HostAlterRoutinePriv> ALTER_ROUTINE_PRIV = createField("Alter_routine_priv", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(com.nextcont.drive.jooq.db.mysql.enums.HostAlterRoutinePriv.class), this, "");

    /**
     * The column <code>mysql.host.Execute_priv</code>.
     */
    public final TableField<HostRecord, HostExecutePriv> EXECUTE_PRIV = createField("Execute_priv", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(com.nextcont.drive.jooq.db.mysql.enums.HostExecutePriv.class), this, "");

    /**
     * The column <code>mysql.host.Trigger_priv</code>.
     */
    public final TableField<HostRecord, HostTriggerPriv> TRIGGER_PRIV = createField("Trigger_priv", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(com.nextcont.drive.jooq.db.mysql.enums.HostTriggerPriv.class), this, "");

    /**
     * Create a <code>mysql.host</code> table reference
     */
    public Host() {
        this("host", null);
    }

    /**
     * Create an aliased <code>mysql.host</code> table reference
     */
    public Host(String alias) {
        this(alias, HOST);
    }

    private Host(String alias, Table<HostRecord> aliased) {
        this(alias, aliased, null);
    }

    private Host(String alias, Table<HostRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "Host privileges;  Merged with database privileges");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mysql.MYSQL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<HostRecord> getPrimaryKey() {
        return Keys.KEY_HOST_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<HostRecord>> getKeys() {
        return Arrays.<UniqueKey<HostRecord>>asList(Keys.KEY_HOST_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Host as(String alias) {
        return new Host(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Host rename(String name) {
        return new Host(name, null);
    }
}
