/*
 * This file is generated by jOOQ.
*/
package com.nextcont.drive.jooq.db.mysql.tables;


import com.nextcont.drive.jooq.db.mysql.Keys;
import com.nextcont.drive.jooq.db.mysql.Mysql;
import com.nextcont.drive.jooq.db.mysql.tables.records.PluginRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * MySQL plugins
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Plugin extends TableImpl<PluginRecord> {

    private static final long serialVersionUID = 493602339;

    /**
     * The reference instance of <code>mysql.plugin</code>
     */
    public static final Plugin PLUGIN = new Plugin();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PluginRecord> getRecordType() {
        return PluginRecord.class;
    }

    /**
     * The column <code>mysql.plugin.name</code>.
     */
    public final TableField<PluginRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CHAR.length(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.CHAR)), this, "");

    /**
     * The column <code>mysql.plugin.dl</code>.
     */
    public final TableField<PluginRecord, String> DL = createField("dl", org.jooq.impl.SQLDataType.CHAR.length(128).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.CHAR)), this, "");

    /**
     * Create a <code>mysql.plugin</code> table reference
     */
    public Plugin() {
        this("plugin", null);
    }

    /**
     * Create an aliased <code>mysql.plugin</code> table reference
     */
    public Plugin(String alias) {
        this(alias, PLUGIN);
    }

    private Plugin(String alias, Table<PluginRecord> aliased) {
        this(alias, aliased, null);
    }

    private Plugin(String alias, Table<PluginRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "MySQL plugins");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mysql.MYSQL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PluginRecord> getPrimaryKey() {
        return Keys.KEY_PLUGIN_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PluginRecord>> getKeys() {
        return Arrays.<UniqueKey<PluginRecord>>asList(Keys.KEY_PLUGIN_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Plugin as(String alias) {
        return new Plugin(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Plugin rename(String name) {
        return new Plugin(name, null);
    }
}
