/*
 * This file is generated by jOOQ.
*/
package com.nextcont.drive.jooq.db.ecm_trans.tables.daos;


import com.nextcont.drive.jooq.db.ecm_trans.tables.FastdfsFilerecord;
import com.nextcont.drive.jooq.db.ecm_trans.tables.records.FastdfsFilerecordRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FastdfsFilerecordDao extends DAOImpl<FastdfsFilerecordRecord, com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.FastdfsFilerecord, String> {

    /**
     * Create a new FastdfsFilerecordDao without any configuration
     */
    public FastdfsFilerecordDao() {
        super(FastdfsFilerecord.FASTDFS_FILERECORD, com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.FastdfsFilerecord.class);
    }

    /**
     * Create a new FastdfsFilerecordDao with an attached configuration
     */
    public FastdfsFilerecordDao(Configuration configuration) {
        super(FastdfsFilerecord.FASTDFS_FILERECORD, com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.FastdfsFilerecord.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.FastdfsFilerecord object) {
        return object.getGlobalid();
    }

    /**
     * Fetch records that have <code>globalId IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.FastdfsFilerecord> fetchByGlobalid(String... values) {
        return fetch(FastdfsFilerecord.FASTDFS_FILERECORD.GLOBALID, values);
    }

    /**
     * Fetch a unique record that has <code>globalId = value</code>
     */
    public com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.FastdfsFilerecord fetchOneByGlobalid(String value) {
        return fetchOne(FastdfsFilerecord.FASTDFS_FILERECORD.GLOBALID, value);
    }

    /**
     * Fetch records that have <code>fid IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.FastdfsFilerecord> fetchByFid(String... values) {
        return fetch(FastdfsFilerecord.FASTDFS_FILERECORD.FID, values);
    }

    /**
     * Fetch records that have <code>groupName IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.FastdfsFilerecord> fetchByGroupname(String... values) {
        return fetch(FastdfsFilerecord.FASTDFS_FILERECORD.GROUPNAME, values);
    }

    /**
     * Fetch records that have <code>fileName IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.FastdfsFilerecord> fetchByFilename(String... values) {
        return fetch(FastdfsFilerecord.FASTDFS_FILERECORD.FILENAME, values);
    }

    /**
     * Fetch records that have <code>extensionsName IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.FastdfsFilerecord> fetchByExtensionsname(String... values) {
        return fetch(FastdfsFilerecord.FASTDFS_FILERECORD.EXTENSIONSNAME, values);
    }

    /**
     * Fetch records that have <code>createTime IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.FastdfsFilerecord> fetchByCreatetime(Timestamp... values) {
        return fetch(FastdfsFilerecord.FASTDFS_FILERECORD.CREATETIME, values);
    }

    /**
     * Fetch records that have <code>updateTime IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.FastdfsFilerecord> fetchByUpdatetime(Timestamp... values) {
        return fetch(FastdfsFilerecord.FASTDFS_FILERECORD.UPDATETIME, values);
    }

    /**
     * Fetch records that have <code>httpEncoding IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.FastdfsFilerecord> fetchByHttpencoding(String... values) {
        return fetch(FastdfsFilerecord.FASTDFS_FILERECORD.HTTPENCODING, values);
    }

    /**
     * Fetch records that have <code>fsRawValue IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.FastdfsFilerecord> fetchByFsrawvalue(String... values) {
        return fetch(FastdfsFilerecord.FASTDFS_FILERECORD.FSRAWVALUE, values);
    }

    /**
     * Fetch records that have <code>path IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.FastdfsFilerecord> fetchByPath(String... values) {
        return fetch(FastdfsFilerecord.FASTDFS_FILERECORD.PATH, values);
    }

    /**
     * Fetch records that have <code>mimeType IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.FastdfsFilerecord> fetchByMimetype(String... values) {
        return fetch(FastdfsFilerecord.FASTDFS_FILERECORD.MIMETYPE, values);
    }
}
