/*
 * This file is generated by jOOQ.
*/
package com.nextcont.drive.jooq.db.ecm_trans.tables.daos;


import com.nextcont.drive.jooq.db.ecm_trans.tables.Meqaupload;
import com.nextcont.drive.jooq.db.ecm_trans.tables.records.MeqauploadRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MeqauploadDao extends DAOImpl<MeqauploadRecord, com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.Meqaupload, String> {

    /**
     * Create a new MeqauploadDao without any configuration
     */
    public MeqauploadDao() {
        super(Meqaupload.MEQAUPLOAD, com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.Meqaupload.class);
    }

    /**
     * Create a new MeqauploadDao with an attached configuration
     */
    public MeqauploadDao(Configuration configuration) {
        super(Meqaupload.MEQAUPLOAD, com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.Meqaupload.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.Meqaupload object) {
        return object.getGlobalid();
    }

    /**
     * Fetch records that have <code>globalId IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.Meqaupload> fetchByGlobalid(String... values) {
        return fetch(Meqaupload.MEQAUPLOAD.GLOBALID, values);
    }

    /**
     * Fetch a unique record that has <code>globalId = value</code>
     */
    public com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.Meqaupload fetchOneByGlobalid(String value) {
        return fetchOne(Meqaupload.MEQAUPLOAD.GLOBALID, value);
    }

    /**
     * Fetch records that have <code>filename IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.Meqaupload> fetchByFilename(String... values) {
        return fetch(Meqaupload.MEQAUPLOAD.FILENAME, values);
    }

    /**
     * Fetch records that have <code>mimetype IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.Meqaupload> fetchByMimetype(String... values) {
        return fetch(Meqaupload.MEQAUPLOAD.MIMETYPE, values);
    }

    /**
     * Fetch records that have <code>contentlength IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.Meqaupload> fetchByContentlength(Integer... values) {
        return fetch(Meqaupload.MEQAUPLOAD.CONTENTLENGTH, values);
    }

    /**
     * Fetch records that have <code>shardsize IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.Meqaupload> fetchByShardsize(Integer... values) {
        return fetch(Meqaupload.MEQAUPLOAD.SHARDSIZE, values);
    }

    /**
     * Fetch records that have <code>createtime IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.Meqaupload> fetchByCreatetime(Timestamp... values) {
        return fetch(Meqaupload.MEQAUPLOAD.CREATETIME, values);
    }

    /**
     * Fetch records that have <code>updatetime IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.Meqaupload> fetchByUpdatetime(Timestamp... values) {
        return fetch(Meqaupload.MEQAUPLOAD.UPDATETIME, values);
    }

    /**
     * Fetch records that have <code>currentshard IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.Meqaupload> fetchByCurrentshard(Integer... values) {
        return fetch(Meqaupload.MEQAUPLOAD.CURRENTSHARD, values);
    }

    /**
     * Fetch records that have <code>partfilesize IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.Meqaupload> fetchByPartfilesize(Integer... values) {
        return fetch(Meqaupload.MEQAUPLOAD.PARTFILESIZE, values);
    }
}
