/*
 * This file is generated by jOOQ.
*/
package com.nextcont.drive.jooq.db.ecm_trans.tables.daos;


import com.nextcont.drive.jooq.db.ecm_trans.tables.Transition;
import com.nextcont.drive.jooq.db.ecm_trans.tables.records.TransitionRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransitionDao extends DAOImpl<TransitionRecord, com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.Transition, String> {

    /**
     * Create a new TransitionDao without any configuration
     */
    public TransitionDao() {
        super(Transition.TRANSITION, com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.Transition.class);
    }

    /**
     * Create a new TransitionDao with an attached configuration
     */
    public TransitionDao(Configuration configuration) {
        super(Transition.TRANSITION, com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.Transition.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.Transition object) {
        return object.getGlobalid();
    }

    /**
     * Fetch records that have <code>globalId IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.Transition> fetchByGlobalid(String... values) {
        return fetch(Transition.TRANSITION.GLOBALID, values);
    }

    /**
     * Fetch a unique record that has <code>globalId = value</code>
     */
    public com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.Transition fetchOneByGlobalid(String value) {
        return fetchOne(Transition.TRANSITION.GLOBALID, value);
    }

    /**
     * Fetch records that have <code>createdate IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.Transition> fetchByCreatedate(Timestamp... values) {
        return fetch(Transition.TRANSITION.CREATEDATE, values);
    }

    /**
     * Fetch records that have <code>requesttype IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.Transition> fetchByRequesttype(String... values) {
        return fetch(Transition.TRANSITION.REQUESTTYPE, values);
    }

    /**
     * Fetch records that have <code>clientid IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.Transition> fetchByClientid(String... values) {
        return fetch(Transition.TRANSITION.CLIENTID, values);
    }

    /**
     * Fetch records that have <code>filename IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.Transition> fetchByFilename(String... values) {
        return fetch(Transition.TRANSITION.FILENAME, values);
    }

    /**
     * Fetch records that have <code>fileid IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.Transition> fetchByFileid(String... values) {
        return fetch(Transition.TRANSITION.FILEID, values);
    }

    /**
     * Fetch records that have <code>length IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.Transition> fetchByLength(Long... values) {
        return fetch(Transition.TRANSITION.LENGTH, values);
    }

    /**
     * Fetch records that have <code>mimetype IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.Transition> fetchByMimetype(String... values) {
        return fetch(Transition.TRANSITION.MIMETYPE, values);
    }

    /**
     * Fetch records that have <code>source IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.Transition> fetchBySource(String... values) {
        return fetch(Transition.TRANSITION.SOURCE, values);
    }

    /**
     * Fetch records that have <code>callbackurl IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.Transition> fetchByCallbackurl(String... values) {
        return fetch(Transition.TRANSITION.CALLBACKURL, values);
    }

    /**
     * Fetch records that have <code>md5digest IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.Transition> fetchByMd5digest(String... values) {
        return fetch(Transition.TRANSITION.MD5DIGEST, values);
    }

    /**
     * Fetch records that have <code>fileextension IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.Transition> fetchByFileextension(String... values) {
        return fetch(Transition.TRANSITION.FILEEXTENSION, values);
    }

    /**
     * Fetch records that have <code>alijobid IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.Transition> fetchByAlijobid(String... values) {
        return fetch(Transition.TRANSITION.ALIJOBID, values);
    }

    /**
     * Fetch records that have <code>filesize IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.Transition> fetchByFilesize(Integer... values) {
        return fetch(Transition.TRANSITION.FILESIZE, values);
    }

    /**
     * Fetch records that have <code>callbacktype IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.Transition> fetchByCallbacktype(String... values) {
        return fetch(Transition.TRANSITION.CALLBACKTYPE, values);
    }

    /**
     * Fetch records that have <code>websocketsessionid IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.Transition> fetchByWebsocketsessionid(String... values) {
        return fetch(Transition.TRANSITION.WEBSOCKETSESSIONID, values);
    }

    /**
     * Fetch records that have <code>errormsg IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.Transition> fetchByErrormsg(String... values) {
        return fetch(Transition.TRANSITION.ERRORMSG, values);
    }

    /**
     * Fetch records that have <code>location IN (values)</code>
     */
    public List<com.nextcont.drive.jooq.db.ecm_trans.tables.pojos.Transition> fetchByLocation(String... values) {
        return fetch(Transition.TRANSITION.LOCATION, values);
    }
}
