/*
 * This file is generated by jOOQ.
*/
package com.nextcont.drive.jooq.db.ecm_trans.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FastdfsFilerecord implements Serializable {

    private static final long serialVersionUID = 1767729973;

    private String    globalid;
    private String    fid;
    private String    groupname;
    private String    filename;
    private String    extensionsname;
    private Timestamp createtime;
    private Timestamp updatetime;
    private String    httpencoding;
    private String    fsrawvalue;
    private String    path;
    private String    mimetype;

    public FastdfsFilerecord() {}

    public FastdfsFilerecord(FastdfsFilerecord value) {
        this.globalid = value.globalid;
        this.fid = value.fid;
        this.groupname = value.groupname;
        this.filename = value.filename;
        this.extensionsname = value.extensionsname;
        this.createtime = value.createtime;
        this.updatetime = value.updatetime;
        this.httpencoding = value.httpencoding;
        this.fsrawvalue = value.fsrawvalue;
        this.path = value.path;
        this.mimetype = value.mimetype;
    }

    public FastdfsFilerecord(
        String    globalid,
        String    fid,
        String    groupname,
        String    filename,
        String    extensionsname,
        Timestamp createtime,
        Timestamp updatetime,
        String    httpencoding,
        String    fsrawvalue,
        String    path,
        String    mimetype
    ) {
        this.globalid = globalid;
        this.fid = fid;
        this.groupname = groupname;
        this.filename = filename;
        this.extensionsname = extensionsname;
        this.createtime = createtime;
        this.updatetime = updatetime;
        this.httpencoding = httpencoding;
        this.fsrawvalue = fsrawvalue;
        this.path = path;
        this.mimetype = mimetype;
    }

    public String getGlobalid() {
        return this.globalid;
    }

    public void setGlobalid(String globalid) {
        this.globalid = globalid;
    }

    public String getFid() {
        return this.fid;
    }

    public void setFid(String fid) {
        this.fid = fid;
    }

    public String getGroupname() {
        return this.groupname;
    }

    public void setGroupname(String groupname) {
        this.groupname = groupname;
    }

    public String getFilename() {
        return this.filename;
    }

    public void setFilename(String filename) {
        this.filename = filename;
    }

    public String getExtensionsname() {
        return this.extensionsname;
    }

    public void setExtensionsname(String extensionsname) {
        this.extensionsname = extensionsname;
    }

    public Timestamp getCreatetime() {
        return this.createtime;
    }

    public void setCreatetime(Timestamp createtime) {
        this.createtime = createtime;
    }

    public Timestamp getUpdatetime() {
        return this.updatetime;
    }

    public void setUpdatetime(Timestamp updatetime) {
        this.updatetime = updatetime;
    }

    public String getHttpencoding() {
        return this.httpencoding;
    }

    public void setHttpencoding(String httpencoding) {
        this.httpencoding = httpencoding;
    }

    public String getFsrawvalue() {
        return this.fsrawvalue;
    }

    public void setFsrawvalue(String fsrawvalue) {
        this.fsrawvalue = fsrawvalue;
    }

    public String getPath() {
        return this.path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getMimetype() {
        return this.mimetype;
    }

    public void setMimetype(String mimetype) {
        this.mimetype = mimetype;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FastdfsFilerecord (");

        sb.append(globalid);
        sb.append(", ").append(fid);
        sb.append(", ").append(groupname);
        sb.append(", ").append(filename);
        sb.append(", ").append(extensionsname);
        sb.append(", ").append(createtime);
        sb.append(", ").append(updatetime);
        sb.append(", ").append(httpencoding);
        sb.append(", ").append(fsrawvalue);
        sb.append(", ").append(path);
        sb.append(", ").append(mimetype);

        sb.append(")");
        return sb.toString();
    }
}
