/*
 * This file is generated by jOOQ.
*/
package com.nextcont.drive.jooq.db.ecm_trans.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransitionFile implements Serializable {

    private static final long serialVersionUID = -1044890634;

    private String globalid;
    private String url;
    private String type;
    private Long   duration;
    private String location;
    private String fullpath;
    private String status;
    private String errormsg;

    public TransitionFile() {}

    public TransitionFile(TransitionFile value) {
        this.globalid = value.globalid;
        this.url = value.url;
        this.type = value.type;
        this.duration = value.duration;
        this.location = value.location;
        this.fullpath = value.fullpath;
        this.status = value.status;
        this.errormsg = value.errormsg;
    }

    public TransitionFile(
        String globalid,
        String url,
        String type,
        Long   duration,
        String location,
        String fullpath,
        String status,
        String errormsg
    ) {
        this.globalid = globalid;
        this.url = url;
        this.type = type;
        this.duration = duration;
        this.location = location;
        this.fullpath = fullpath;
        this.status = status;
        this.errormsg = errormsg;
    }

    public String getGlobalid() {
        return this.globalid;
    }

    public void setGlobalid(String globalid) {
        this.globalid = globalid;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Long getDuration() {
        return this.duration;
    }

    public void setDuration(Long duration) {
        this.duration = duration;
    }

    public String getLocation() {
        return this.location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getFullpath() {
        return this.fullpath;
    }

    public void setFullpath(String fullpath) {
        this.fullpath = fullpath;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getErrormsg() {
        return this.errormsg;
    }

    public void setErrormsg(String errormsg) {
        this.errormsg = errormsg;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TransitionFile (");

        sb.append(globalid);
        sb.append(", ").append(url);
        sb.append(", ").append(type);
        sb.append(", ").append(duration);
        sb.append(", ").append(location);
        sb.append(", ").append(fullpath);
        sb.append(", ").append(status);
        sb.append(", ").append(errormsg);

        sb.append(")");
        return sb.toString();
    }
}
