/*
 * This file is generated by jOOQ.
*/
package com.nextcont.drive.jooq.db.ecm_trans.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransitionCallback implements Serializable {

    private static final long serialVersionUID = 1090998980;

    private String    globalid;
    private String    fileid;
    private String    status;
    private String    info;
    private String    callbackurl;
    private Timestamp createtime;
    private Byte      aggregationstatus;
    private String    iconlink;

    public TransitionCallback() {}

    public TransitionCallback(TransitionCallback value) {
        this.globalid = value.globalid;
        this.fileid = value.fileid;
        this.status = value.status;
        this.info = value.info;
        this.callbackurl = value.callbackurl;
        this.createtime = value.createtime;
        this.aggregationstatus = value.aggregationstatus;
        this.iconlink = value.iconlink;
    }

    public TransitionCallback(
        String    globalid,
        String    fileid,
        String    status,
        String    info,
        String    callbackurl,
        Timestamp createtime,
        Byte      aggregationstatus,
        String    iconlink
    ) {
        this.globalid = globalid;
        this.fileid = fileid;
        this.status = status;
        this.info = info;
        this.callbackurl = callbackurl;
        this.createtime = createtime;
        this.aggregationstatus = aggregationstatus;
        this.iconlink = iconlink;
    }

    public String getGlobalid() {
        return this.globalid;
    }

    public void setGlobalid(String globalid) {
        this.globalid = globalid;
    }

    public String getFileid() {
        return this.fileid;
    }

    public void setFileid(String fileid) {
        this.fileid = fileid;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getInfo() {
        return this.info;
    }

    public void setInfo(String info) {
        this.info = info;
    }

    public String getCallbackurl() {
        return this.callbackurl;
    }

    public void setCallbackurl(String callbackurl) {
        this.callbackurl = callbackurl;
    }

    public Timestamp getCreatetime() {
        return this.createtime;
    }

    public void setCreatetime(Timestamp createtime) {
        this.createtime = createtime;
    }

    public Byte getAggregationstatus() {
        return this.aggregationstatus;
    }

    public void setAggregationstatus(Byte aggregationstatus) {
        this.aggregationstatus = aggregationstatus;
    }

    public String getIconlink() {
        return this.iconlink;
    }

    public void setIconlink(String iconlink) {
        this.iconlink = iconlink;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TransitionCallback (");

        sb.append(globalid);
        sb.append(", ").append(fileid);
        sb.append(", ").append(status);
        sb.append(", ").append(info);
        sb.append(", ").append(callbackurl);
        sb.append(", ").append(createtime);
        sb.append(", ").append(aggregationstatus);
        sb.append(", ").append(iconlink);

        sb.append(")");
        return sb.toString();
    }
}
